### ISSUE TITLE
Range of dct:type

### ISSUE THREAD

**Issue by wood-chris** [w3c/dxwg#1009]
In DCAT v2, the property`dct:type` in the class of `dcat:Resource` has range of `rdfs:Class`, with a usage note of:

> The value SHOULD be taken from a well governed and broadly recognised controlled vocabulary, such as:
DCMI Type vocabulary [DCTERMS]
[...]

I've got 2 questions about this

1. I see that all classes listed in DCMI Type are of type `rdfs:Class`, as I'd expect, but I don't see how any of the 12 classes given can be used to describe the _nature or genre_ of a dataset in a way that the `dct:theme` property can't? (i.e. what was/is the rationale? what should be described using `dct:property` that can't be described with `dct:theme`?) 
2. what properties can be applied to instances of DCMI Terms? Is the _controlled vocabulary_ just the list of the 12 classes? Or is there a richer set of terms somewhere that I haven't yet found?

**Comment by dr-shorthair** [comment]
1. the intention of `dct:type` and `dcat:theme` are different. 'theme' is a keyword _from a controlled vocabulary_ - i.e. from a well-governed set of terms, and not just free text - and would usually relate to the **content** of the dataset. OTOH 'type' is usually more related to the **form** or **structure** of the dataset. 
Note, both of these properties were present in DCAT-2014 and there has been no other suggestion to remove or merge either. 

2. Not sure I understand the issue here. A DCMI Term would normally be denoted by its URI as a reference in a DCAT record. So there are no new instances or properties thereof.

**Comment by makxdekkers** [comment]
@wood-chris As I see it, the dct:type of a described resource is what it *is* while `dcat:theme` (or `dct:subject` of which it is a subproperty) is what it *is about*. E.g. a book about cats has `dct:type`=Book and `dcat:theme`=Cats -- in which both Book and Cats would be represented by URIs.
The list of 12 types in DCMI Type is just a very general list that was thought to be useful across domains. In specific domains, you can have other, more specific lists, e.g. the one at https://publications.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/resource-type/ for EU legal resources.

**Comment by kcoyle** [comment]
Unfortunately I think it is even more complex, although it may be a complexity that isn't significant for all communities.

1. dct:Type vocabulary describes a created work expression form: text, sound recording, moving image. 
1. dct:format describes the physical or digital carrier for the expression.
1. "genre" (in metadata that I am familiar with) speaks to a category or role of the content, such as "review article" or "executive summary" or "statistical analysis". 
1. dcat:theme and dct:subject seem to pretty clearly cover the "aboutness" aspect.

It's fairly common for communities to mix together terms from type, format and genre, often because they aren't clear on how the differences are significant for their data. At the same time, it is hard enough to explain to data creators what the differences between these are and users rarely are cognizant of them. Even where data has been created with distinct terms it has at times been necessary to combine them for end-user searching because users don't understand them.

As for @wood-chris's questions:

1. As Makx points out, dct:Type vocabulary and dcat:theme cover very different aspects of a resource. If you have a type of "moving picture" (aka: a film) that is quite different from a resource (e.g. a book) that is about moving pictures. Ideally these two concepts would have different identifiers. 
1. Sadly, dct:type includes "type or genre" in its definition, so it fails to clarify that difference. Thinking in this area as evolved since the DC Terms were defined.
1. There are richer type or genre vocabularies if you wish to use them, but be beware of mixes of expression type and genre - or at least be careful what you do with them. There is the [genre list](http://www.loc.gov/standards/valuelist/marcgt.html) used by libraries which now has a [SKOS version ](http://id.loc.gov/authorities/genreForms.html)(e.g. search on "[book](http://id.loc.gov/search/?q=book&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2FgenreForms)"). But note that even this _list_ combines form and genre because they had been combined in the past; the input rules assign these concepts to different metadata elements in current data. (There are also specific lists for specific expression types, analogous to the legal list that Makx refers to, because specialist collections generally need more detail than general ones. For example, there is a list of musical expression types that is quite extensive and is used when describing musical works.)

**Comment by wood-chris** [comment]
I hadn't understood what DCMI Terms was (and I'm not sure I really still do, or maybe the organic evolution makes more sense if you've seen the evolution!), but the example given by @makxdekkers has helped. I had always assumed that _genre_ was used to describe data, rather than its format. (In music, genre would be how we define the music, rather than its format, such as saying it is a CD).

@kcoyle thanks for all the links, and the explanations

@dr-shorthair I didn't intend to imply I thought the terms should be merged :) I was using this as a replacement for an email list (I couldn't see an obvious discussion list to send this question to).

**Comment by makxdekkers** [comment]
@wood-chris Apparently, my post wasn't really helpful because your conclusion was completely contrary to what I tried to argue. "CD" would not be a `dct:type` but would be a `dct:format`. The example of a type "Book" that I mentioned, is not a format; its format would be "Hardcover" or "paperback" or "ePub".
The property `dct:type` refers to the _kind of thing_ the resource is. As far as I can see, the example of the types in the list at https://publications.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/resource-type/ might make this clearer -- or would you consider those types of legal resources formats? 
As to your example of genres in music, I don't have experience in that domain, but it seems to me that on a high level , the `dct:type` of music in general would be `dcmitype:Sound`, and if you have a more specific type list it could be foo:ClassicalMusic, foo:PopMusic, etc etc., so the kind of music -- to whatever level of detail your list supports.
As to the organic evolution, I don't think there has been any: the DCMI terms (the set of properties) and the DCMI types (the list of 12 resource types) have been stable for almost two decades.

**Comment by wood-chris** [comment]
@makxdekkers - sorry, I think I mixed terms up; your original answer did help more than I think you thought it did.

Cambridge Dictionaries define genre as:

> a style, especially in the arts, that involves a particular set of characteristics:
What genre does the book fall into - comedy or tragedy?

I think my confusion was that `dct:type` is defined as _The nature or genre of the resource._ - but without realising just _how_ wide the spectrum it covers was. I probably know even less about legal documents than you do about music :) but from looking at that list I can see why they're _types_ (and not formats) - although they're between the extremes of the spectrum of `dcmi:Text` and something as finely grained as some specific music genres (e.g. https://musicbrainz.org/genres)!

**Comment by davebrowning** [comment]
Can I assume that this issue can be closed - its been a useful discussion but needs no change to the DCAT draft?
