### ISSUE TITLE
Features at risk/Implementation evidence

### ISSUE THREAD

**Issue by davebrowning** [w3c/dxwg#1025]
The DCAT 2 recommendation includes some new features which may have implementation maturity concerns - essentially that adequate implementation evidence won't be available in the timeframe we plan to move to approval.  [Examples could be some of the geospatial elements, and/or the qualified relation section]

Where this is possible, these sections should be marked at 'Feature at Risk' as the document goes through CR.  For subsequent transition to PR, such sections would need to be no longer at risk, removed completely or marked as non-normative.

(See discussion at end of DCAT meeting minuted at https://www.w3.org/2019/07/31-dxwgdcat-minutes, including links to examples)

**Comment by dr-shorthair** [comment]
Features likely at risk:
 
- `dcat:service`
- `dcat:catalog`
- `dcat:accessService`
- `dcat:packageFormat`
- `odrl:hasPolicy`
- `dcat:qualifiedRelation`
- `prov:qualifiedAttribution`
- `prov:wasGeneratedBy`
- `dcat:Relationship`
- `dcat:hadRole`
- `dcat:Role`
- `dcat:startDate`
- `dcat:endDate`
- `dcat:bbox`
- `dcat:centroid`
- `dcat:spatialResolutionInMeters`
- `dcat:temporalResolution`

**Comment by larsgsvensson** [comment]
In case it helps, DNB uses `dcat:compressFormat`, cf. https://d-nb.info/datasets/authorities_20190328.ttl

**Comment by davebrowning** [comment]
@nicholascar At the plenary you asked which properties might be in the at risk category

**Comment by nicholascar** [comment]
The DCAT *view* ('profile') of the [Geofabric Linked Data](linked.data.gov.au/dataset/geofabric) dataset in RDF (turtle), http://linked.data.gov.au/dataset/geofabric?_view=dcat&_format=text/turtle,  shows that it's using:

* `dcat:DataService`
* `dcat:servesDataset`
* `dcat:endpointDescription`

And, with little work, we cna probably get it to to deliver these as well:

* `prov:wasGeneratedBy`
* `dcat:accessService`
* `dcat:hadRole`
* `dcat:Role`
* `dcat:bbox`

This will all be x3 since there are another two Datasets like this ([Geocoded National address File, Linked Data](http://linked.data.gov.au/dataset/gnaf) & [Australian Statistical Geographies Standard, Linked Data](http://linked.data.gov.au/dataset/asgs2016)).

Additionally, I will try and speed up the annotation of datasets in the [GSQ Open Data Portal](https://horizon.gsq.digital/), which uses CKAN, with DCAT 2 terms.

**Comment by dr-shorthair** [comment]
@nicholascar I see that it currently is showing `dcat:DataDistributionService` which was removed a few months ago. `dcat:DataService`, with `dct:type <https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/download> ;` is recommended now - see https://w3c.github.io/dxwg/dcat/#ex-service-gsa

**Comment by nicholascar** [comment]
@dr-shorthair yes, I'm aware of the need to update some out-of-date things. Which is why I wanted this at-risk list now so I can do one-time updates to all the RDF.

Have just arranged update processes for me with repo owners.

**Comment by andrea-perego** [comment]
@dr-shorthair , I would remove the following properties from the list of features at risk, as they are already implemented (see [implementation evidence spreadsheet](https://docs.google.com/spreadsheets/d/1eEVUuPFAGO2GjS5ocxylY8T1AlpqlwnOTc3er_Mhcv4/edit#gid=1108132380)):
- `dct:accessRights`: it is supported on different classes by DCAT-AP, GeoDCAT-AP, CiteDCAT-AP, and DCAT-AP-JRC
- `dct:isReferencedBy`: it is supported by CiteDCAT-AP and DCAT-AP-JRC
