### ISSUE TITLE
PROF in normative areas of Conneg

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#1118]
The profiles vocabulary (PROF) is integrated into normative sections of the document, in particular section 7.3.1.1 and Appendices, in particular A.1. These appear to be normative based on the conformance section statement:

"As well as sections marked as non-normative, all authoring guidelines, diagrams, examples, and notes in this specification are non-normative. Everything else in this specification is normative."

It is inadvisable to move Conneg to CR with a non-normative document (PROF) in normative sections of the document. By "inadvisable" it really means that it is unlikely to be approved for CR. The reason for this is that once a document becomes a recommendation it is very costly and difficult to make changes to it - basically, it is like the process that we have gone through between DCAT v1 and DCAT v2 - a charter, group formation, and an entirely new recommendation path. Having Conneg depend on a vocabulary "in progress" definitely puts Conneg at risk, and would require convincing W3C management, who will likely challenge the proposed recommendation, that this is a good idea.

We should not move Conneg forward "as is" but there are various options we can consider for Conneg, some of which are:

1. Move sections referring to PROF to non-normative areas of the document.
2. Remove references to PROF.
3. Advance Conneg as a working group note rather than CR track.

**Comment by rob-metalinkage** [comment]
Good catch - 

what we need to do is explicitly declare the appendices as non-normative - its natural but not safe to assume that would be the case,

I think we can remove the reference to prof:Profile in 7.3.1 because dct:conformsTo is sufficient (though we may need to make statement that any dct:Standard referenced this way is assumed to be an instance of a "data profile" - we can refer to appendix as an example of how to make this explicit, )

**Comment by nicholascar** [comment]
I have removed all references to PROF in PR #1120 and emphasised in *Conformance* that appendices are non-normative.

**Comment by kcoyle** [comment]
Closing as the changes were made in #1120.
