### ISSUE TITLE
specification of range restrictions

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1129]
Hi,

in https://w3c.github.io/dxwg/dcat/#Property:distribution_compression_format it is stated that the range is restricted to be a iana Mediatype.

In https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat.ttl the range is dct:MediaType.
Q1: Is there another Machine readible document, like shacl, that expresses then the restriction?

Also, not all language definitions in https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat.ttl mention this restriction. 
Q2: Is there a policy here? what is part of the definition and what not. 

For me the definition of the property is without the restriction. The restriction is an additional contraint. Using another controlled vocabulary does not change the meaning/semantics of the property.

**Comment by riccardoAlbertoni** [comment]
Labelled "future-work" as for discussion in the [2019-11-05 telecon](https://www.w3.org/2019/11/05-dxwg-minutes.html)  and  related [resolution](https://www.w3.org/2019/11/05-dxwg-minutes.html#resolution05)

**Comment by riccardoAlbertoni** [comment]
Hi @bertvannuffelen, 
Thanks for your comments and our apologies for this late reply. We discussed this issue during last week's [DCAT submeeting](https://www.w3.org/2021/04/14-dxwgdcat-minutes). 
 I am going to report the main points of the discussion below after your questions.

> Q1: Is there another Machine readible document, like shacl, that expresses then the restriction?

No, there isn't,  and we are not considering having it, at least for the moment. 
We provide the  DCAT RDF to ease the DCAT adoption, but the HTML document is the actual DCAT recommendation, which is the only expected to say what is recommended or not in the W3C  Standardization Process. 

> Also, not all language definitions in https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat.ttl mention this restriction.

 We did our best to maintain the translations updated in the DCAT 2 RDF. However, keeping the translations updated requires revising in different languages every time a piece of definition changes, forcing complex interactions among translators. Also, the translators are volunteers not always available in the timeframes we need. 

Due to these difficulties,  we have agreed on a new policy for the translations in DCAT 3. The current deal is to maintain the English definitions while specifying DCAT 3 and ask for translations on the best-effort basis once we get a stable document at the CR phase (see issue #1352).

> Q2: Is there a policy here? what is part of the definition and what not.
> 

The following excerpt is taken from the [section conformance](https://www.w3.org/TR/vocab-dcat-2/#conformance) and gives the policy to interpret the DCAT document.
 
"As well as sections marked as non-normative, all authoring guidelines, diagrams, examples, and notes in this specification are non-normative. Everything else in this specification is normative.
The key words MAY, MUST, MUST NOT, and SHOULD in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here."

> For me the definition of the property is without the restriction. The restriction is an additional contraint. Using another controlled vocabulary does not change the meaning/semantics of the property.

In the specific case, we use   “SHOULD” explicitly referring to the RFC 2119 in a normative section, which implies that using this property with IANA mediaType is recommended unless there is a valid reason to ignore the indication. 

Using all the same code list improves interoperability, so I think here the suggestion is to use IANA for media type. Different courses are possible according to DCAT 2, but the full implications must be understood and carefully weighed before choosing a different course.

Do the above comments clarify your doubts? in this case, can we close this GitHub Issue, or do you think further related aspects need to be considered?

**Comment by andrea-perego** [comment]
@riccardoAlbertoni said:

> Do the above comments clarify your doubts? in this case, can we close this GitHub Issue, or do you think further related aspects need to be considered?

@bertvannuffelen , as we didn't get any further feedback, we are closing this issue.
