### ISSUE TITLE
dcat:landingPage - check constraints

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#122]
In DCAT v1 the property `dcat:landingPage` is axiomatized 
```
dcat:landingPage
  rdf:type owl:ObjectProperty ;
  rdfs:domain dcat:Dataset ;
  rdfs:range foaf:Document ;
  rdfs:subPropertyOf foaf:Page ;
.
```

1. Verify that the range is appropriate and necessary
2. Verify that the domain is appropriate and necessary (see #110)
3. Consider whether any guarded constraints (using owl:Restriction) should be introduced (see #105)

**Comment by dr-shorthair** [comment]
sub-property axiom is incorrect - foaf:Page is a class. 
foaf:page is probably the intended property.

**Comment by dr-shorthair** [comment]
range constraint is redundant since it is inherited from foaf:page

**Comment by dr-shorthair** [comment]
dcat:landingPage is essentially an alias for foaf:page in the context of dcat:Dataset. 
The goal appears to be to allow a link to a page which would list available distributions for a Dataset. 
I wonder if it would be better to make that intention more explicit by making the range a more specific class, like "dcat:DistributionList". 

Otherwise, I don't really see that dcat:landingPage offers anything not already provided by foaf:page, unless it is merely to overcome a general reluctance to build FOAF elements directly into DCAT.

**Comment by andrea-perego** [comment]
I tend to agree.

However, there may be a requirement for relaxing its domain restriction in case we decide that a catalogue can contain records about resources that are not datasets (as services). In such a case, `dcat:landingPage` 
may be extended to other resource types.

Also, I wonder whether DCAT doesn't use `dcat:landingPage` also for `dcat:Catalog`'s - need to check if the reason is documented in the GLD WG issue tracker.

**Comment by dr-shorthair** [comment]
I was trying to figure out if there was a solid reason why foaf:page could not be the general solution?  
dcat:landingPage would then remain associated only with Datasets, and reserved for a link to a _DistributionList_ (sometimes called 'alternates view').

**Comment by makxdekkers** [comment]
@dr-shorthair Narrowing the range from `foaf:Document` to `dcat:DistributionList` could break existing implementations, so I don't think we should do that.

**Comment by dr-shorthair** [comment]
Would it? 

It would entail that whatever they linked to is a DistributionList. OWA means that there are no specific expectations about what properties that has.

**Comment by makxdekkers** [comment]
Well... Wouldn't it be odd if the landing page did not in fact list any distributions? I agree that there is probably no formal expectation under OWA -- after all, the software can't actually _read_ the document -- but from a human perspective, you would expect a dcat:DistributionList to contain a list of distributions, wouldn't you? If not, what's the point?

**Comment by fellahst** [comment]
In Geoplatform profile, we introduced a superclass of dcat:Dataset called Asset. We use the property landing page to indicate that there is a web page that represents the asset.  In the case of a Map or Layer (subclasses of Asset), the landing page typically corresponds to a map viewer with the map or a layer (ex: https://geoplatform.maps.arcgis.com/home/webmap/viewer.html?webmap=b2c3ef22c8c14c2da57b243f2d04bd86), or a page describing the metadata about the artifact. 
I think dcat:landingPage provides a more precise semantic than foaf:page. It is very close to foaf:homepage (we may want to introduce owl:equivalentProperty axiom)

Thus here are my recommendations:

1) Remove the domain dcat:Dataset from dcat:landingPage
2) Keep the range to foaf:Document
3) fixed the subproperty to foaf:page instead of foaf:Page.

**Comment by dr-shorthair** [comment]
@makxdekkers I would like to bottom this out. 
1. What does a dataset landing page show, apart from a list of (maybe just one) distributions or service-calls? 
2. If there is no particular expectation or contraint on what a landing page is, then is just a local alias for foaf:page? (above I asked if it was just merely to overcome a general reluctance to build FOAF elements directly into DCAT.)

**Comment by makxdekkers** [comment]
@dr-shorthair OK let's do that!
From my perspective, there are two levels to the issue.
1. the _specific_ issue of whether it is reasonable to expect, or necessary to require, that the object of `dcat:landingPage` is something that contains a list of (links to) distributions, and also what the objective is of narrowing its range.
2. the more _general_ issue of what the conditions are under which the semantics of an existing property may be narrowed.

On the specific issue, my opinion is that, yes, it is probably reasonable to expect that you'll get a list of distributions on a landing page, but, no, we shouldn't require it because there may be actual cases that a landing page doesn't list distributions. The other question is what we would gain by narrowing the range. Would we want to tell people what we think is a 'good' landing page, and prevent people from using the property with a 'bad' landing page? I am not so sure.

On the general issue, we may need to have a more fundamental discussion. There my position would be: "don't do it, unless it is absolutely necessary".

**Comment by makxdekkers** [comment]
@dr-shorthair On your second question, I think there is a clear difference between 

`foaf:page`: A page or document about this thing.
`dcat:landingPage`: A Web page that can be navigated to in a Web browser to gain access to the dataset, its distributions and/or additional information.

First of all, `dcat:landingPage` must be a Web page while `foaf:page` allows as object "_things which are, broadly conceived, 'documents'_". Secondly, `foaf:page` links to information "_about this thing_" while dcat:landingPage requires information that serves "_to gain access to the dataset, its distributions and/or additional information_". To me, these two specialisations of `foaf:page` justify the existence of the DCAT property.
Please also note that in the European DCAT-AP both `dcat:landingPage` and `foaf:page` are specified for Dataset, the latter to allow a link to any kind of documentation about the dataset.

**Comment by dr-shorthair** [comment]
Thanks @makxdekkers . 

Good - that helps. I don't actually have much investment in the outcome here, just aiming for clarity. 

On the first issue, perhaps the documentation of dcat:landingPage 
https://w3c.github.io/dxwg/dcat/#Property:dataset_landingpage could be improved to indicate that landing-page is usually a list of distributions or links to service-calls that provide distributions. 

I understand your backward compatibility concerns. At an earlier phase of the conversation you were keen to drop all domain constraints except the ones that were absolutely needed, but then I think you saw some risks. Fair enough. In the other W3C project I was involved in recently (SSN) the backward compatibility concerns were less because the prior version was not a W3C Recommendation, merely an incubator report, so no representations of stability had ever been made. DCAT is different. 

My general observation is that global domain constraints are unfortunately one of the most misunderstood and thus misused parts of RDF. Folk tend to think of them as just supporting data modelling, rather than asking the question "Is it OK that every time property-a is used in a dataset, the implication is that the subject is a member of class-C?" I'm more comfortable with global range constraints, since it is reasonable that the intention of a property definition is somehow tied up with the target object type. 

Thanks for pointing out the looser definition of the range of foaf:page - I hadn't processed that.

@andrea-perego I think your argument for loosening the domain of dcat:landingPage is so you could use it to point to records of services as well as datasets. That usage is parallel to the dcat:dataset link from a Catalog to a Dataset? Wouldn't it be better to officially accommodate services in the catalog? e.g. like this https://github.com/w3c/dxwg/wiki/Data-service Otherwise it feels a bit coy, sneaking in service-cataloging through 'creative' use of some existing classes and properties, rather than recognising that this is a real requirement (with two Use Cases behind it).

**Comment by arminhaller** [comment]
+1 to @fellahst

**Comment by makxdekkers** [comment]
@dr-shorthair Please note that my earlier idea to drop domain constraints was strictly about relaxing/widening, never about narrowing semantics. But yes, there are consequences and risks that need to be analysed under the specific properties.

**Comment by dr-shorthair** [comment]
https://www.w3.org/2018/03/21-dxwgdcat-minutes
resolved: relax/remove domain constraint on dcat:landingPage
resolved: no change to range of dcat:landingPage

**Comment by dr-shorthair** [comment]
See #171
