### ISSUE TITLE
Including more machine-actionable Version Delta?

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1271]
Besides the human-readable descriptions of the changes, we might want to discuss suggestions on also considering more machine-friendly references.

**Comment by andrea-perego** [comment]
Relevant comments from https://github.com/w3c/dxwg/issues/89:

>What about a pointer to a Git transaction?
_Originally posted by @nicholascar in https://github.com/w3c/dxwg/issues/89#issuecomment-368896015_ 

>I quite like the idea of a Git transaction but not all new versions would naturally be picked up that way, I think.  For those that do, then perhaps we should encourage it
An example where the textual approach works better would be where a publisher has changed coverage in some way, but the rest stays the same.  [This is fairly common practice with financial data - I may have a dataset that claims to cover corporates across the EU for example but has systematic issues for the UK (for example).  When I address those issues, I may want to treat it as a new version of the original dataset rather than a new dataset as a way of signaling to users that its an important change but still an evolution of what I produced before]  This is all information domain-specific, of course.
_Originally posted by @davebrowning in https://github.com/w3c/dxwg/issues/89#issuecomment-368914163_

**Comment by andrea-perego** [comment]
Not seeing any additional reaction on this issue, I would like to propose a vote to understand how to move this forward:

1. Let's close this issue - currently there's no evidence that this issue is supported by any use case
2. Let's discuss this issue further - there may be use cases out there we should find out

In case you vote for option (2), if you have or are aware of any use case, please share it here.

**Comment by andrea-perego** [comment]
Noting no reaction, I'm flagging this issue as due for closing.

**Comment by andrea-perego** [comment]
Closing it.
