### ISSUE TITLE
Use PROV-O to satisfy provenance requirements

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#128]
A number of the formal requirements could be satisfied relatively easily through use of PROV-O properties. 
In particular: 

#78 if `dcat:CatalogRecord` was modeled as a subclass of `prov:Entity`
#77 , #76 , #71 , #66 , #63 ,   if `dcat:Dataset` was a subclass of `prov:Entity`

and probably also the issues tagged 'quality'. 

PR #94 already implements the second of these cases, but there is discussion on whether a subsumption axiom is warranted, else we should merely recommend the use of PROV-O properties without the formal classifier.

**Comment by rob-metalinkage** [comment]
Is there an issue here that use of prov:properties may not entail dcat:Dataset  a subclass of prov:Entity because, for example

 prov:wasInfluencedBy rdfs:domain [ owl:unionOf (prov:Activity prov:Agent prov:Entity) ]

whereas we might want to be explicit that a dcat:Dataset was a subclass of prov:Entity

given PROV-O as a w3c rec, my feeling it is useful to model these explicitly if inferencing can't be easily done.

**Comment by aisaac** [comment]
I really don't understand the logic of why the subclass axiom to prov:Entity would be needed. To me, putting a subclass axiom to prov:Entity should be the last thing to do.

Here's the reasoning: in matters of PROV re-use, what is important is to tell which PROV properties and patterns DCAT implementers/users should use (especially because it's not easy to orient oneself into the PROV patters, which can be complex). In other words, it's important that we say things like "if you want to meet requirement X, then you should use prov:wasInfluencedBy". Stating that dcat:Dataset is a subclass of prov:Entity doesn't help satisfying any requirement per se.
 
This is in a way what was done for the Data Quality Vocabulary (https://www.w3.org/TR/vocab-dqv/): we meet our requirements without explicitly suclassing dcat:Dataset. Yet DQV uses PROV.

(and putting here a cross-reference to #94)

**Comment by dr-shorthair** [comment]
(Moving discussion here from #94)

Over at https://github.com/w3c/dxwg/pull/94#issuecomment-365867941 @aisaac wrote: 

> it adds one class to the DCAT mix, it diverts attention to what really matters (i.e. which parts of PROV to re-use besides prov:Entity)

I would say in principle there is no limit to which parts of PROV may be re-used. The more I explore PROV, the more byways I find myself traveling down. So I only see opportunities, not risks. 

I note your comment about what was done in DQV. However, I also see that some of DQV is sub-classed from QB, which brings plenty of its own baggage. So perhaps you can explain why that made sense, while subclassing dcat:Dataset from prov:Entity doesn't. The scope of DCAT has a significant overlap with the scope of PROV. PROV is a W3C vocabulary.

**Comment by aisaac** [comment]
@dr-shorthair sure PROV brings a lot of good opportunities, I'm 100% with you on this. It's just that I am not comfortable with 'importing' elements when they do not bring obvious value. Actually I may not object to the subclass axiom in the end. But that's the point: assessing it as one of the later steps, if we observe that all the more obviously useful PROV elements that we will have imported to meet our requirements would need this subclass axiom.

As for DQV, some of its elements are subclasses to QB because the subclassing brings some useful semantics (formal or informal). Let's look at dqv:QualityMeasurement. It is a subclass of qb:Observation ("A single observation in the cube, may have one or more associated measured values"). But what would dqv:QualityMeasurement be without that subclass axiom? We would have had to redefine quite some fine-grained stuff, including what is an observation, and make our own reference to data cubes. This is quite a contrast with the 'gain' of subclassing dcat:Dataset with prov:Entity. When one knows a resource is a dataset, it doesn't bring much more to know that it is also "a physical, digital, conceptual, or other kind of thing with some fixed aspects; [which] may be real or imaginary." (the definition of prov:Entity)

**Comment by rob-metalinkage** [comment]
Just to note, if we want use DQV, and it imports QB, this makes it easy for us to use QB to define finer grained semantics (not that there is much better choice).  It has pretty much everything we need IMHO - the ability to define subsets, bind schemas to vocabularies.  What it is missing is a canonical way to bind a rdf property name to a structural element in non RDF encodings - or to put it the other way, we need to be able to describe data set structures independently of the encoding of distributions and create resource identifiers for structural elements.  What is the best the candidate vocabulary for this? 

The issues I have found looking at profiles in the context of QB is one needs to define an entailment regime for inheritance/dependency in the constraint model - much the same way SKOS defines how skos:broader and skos:broaderTransitive relate.   This is pretty much exactly the same problem we have for profiles in general, and profile description languages will need to follow.  Using QB would make profile description relatively simple - so if it can get elevated to at least documented BP guidance thats great, and making sure dcat allow this, and does not overspecify half-solutions is the key.

**Comment by dr-shorthair** [comment]
@rob-metalinkage This issue is not about use of QB in DCAT. 
@aisaac pointed to it as an example of where subclassing PROV was considered and rejected. 

So I was trying to figure out why sub-classing from QB made sense and PROV not in the context of DQV, in case that provides insight about the condition necessary for sub-classing from a (different) elaborate dependency. 

Lets try to keep the threads clean folk!

**Comment by rob-metalinkage** [comment]
The pattern is the same - i was expanding on it here in the context of working out the criteria: for any given vocabulary X it has some axiomatised semantics (which may or may not make things difficult) and entailment rules and expectations.  That said - it would be better if i had put details in a discussion about fine grained semantics and vocabulary re-use and cross linked it here where the active discussion seems to be.

**Comment by dr-shorthair** [comment]
Maybe put the PROV alignment in a separate graph (file) - see #111

**Comment by dr-shorthair** [comment]
Adjusted #94 to match.

**Comment by dr-shorthair** [comment]
This RDF file https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/prov.ttl 
imports DCAT and PROV-O, and includes some basic alignment axioms. 
This may be used in datasets to explore the use of PROV capabilities in recording detailed provenance information relating to DCAT artefacts (mostly datasets and catalog records?)

**Comment by dr-shorthair** [comment]
#312 begins the formal introduction of elements from PROV-O into DCAT

**Comment by dr-shorthair** [comment]
The DCAT team has resolved to adopt elements from the PROV-O vocabulary for use in the context of individual of type dcat:Dataset (at least). There is no need to formally axiomatize 
```
dcat:Resource rdfs:subClassOf prov:Entity . 
```
because the PROV properties `prov:wasGeneratedBy`, `prov:wasDerivedFrom` and `prov:wasAttributedTo` have a global domain constraint which has that entailment anyway. So if you tag a dataset using one of these properties you imply that is it a `prov:Entity`, but if you don't, then this entailment does not follow. 

Anyway, since we have agreed to use PROV-O properties, I think this issue is now resolved.
