### ISSUE TITLE
Should we turn 'dct' into 'dcterms' also for the GitHub examples?

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1319]
Apparently, DCAT 2 REC points to the GitHub examples directly, so if we change dct in there, we will lose the coherence with the  DCAT 2 REC.

I see three options:
1) we wait for changing the examples till the very last moment before publishing dcat 3 CR. 
2) we create a brand new copy of the directory 'examples/' named 'exampleDCAT3',  in which dct is replaced by dcterms and we keep the pointed files in 'examples/' coherent with DCAT 2 REC; 
3) we change the namespace and lose the coherence of examples with the current REC, as in the end, having dct in the rec and dcterms in the examples is not a big issue.

Any specific preferences on how to proceed?

_Originally posted by @riccardoAlbertoni in https://github.com/w3c/dxwg/issues/1316#issuecomment-794303548_

**Comment by andrea-perego** [comment]
I think the problem with option (3) is that we have already modified some examples in the draft of the DCAT3 spec, and added new ones.

So, I guess we should anyway maintain the examples of the different versions of DCAT separately, and go for option (2). We just have to decide where to place them. E.g., instead of creating a new folder under `dcat/`, an option is to have subfolders for each DCAT version under `examples/` (`examples/vocab-dcat-3/`, etc.).
