### ISSUE TITLE
Relax range restriction on dcat:theme

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1364]
@dr-shorthair 

Why not relax range constraint for `dcat:theme`? In the biomedical domain we have more ontologies and often these ontologies have `owl:Class` typing for concepts.

_Originally posted by @rajaram5 in https://github.com/w3c/dxwg/issues/123#issuecomment-843290546_

**Comment by agbeltran** [comment]
There was also a discussion around the range for ```dcat:theme``` at: https://github.com/w3c/dxwg/issues/1153

**Comment by dr-shorthair** [comment]
I would be comfortable relaxing the ranges of theme and themeTaxonomy. But it is important to keep them as object-properties, since the object must be denoted by a URI - i.e. taken from a managed source somewhere.

**Comment by makxdekkers** [comment]
All, there was an earlier discussion on this (see [here](https://github.com/w3c/dxwg/issues/1153#issuecomment-549750210)), where I noted that `dcat:theme` was explicitly minted for DCAT version 1 because it was felt that the range of `dct:subject` was too broad and that it would be useful to have a property with a range restricted to `skos:Concept`. Otherwise, `dct:subject` could have been used.
Now, with the relaxation of the range of `dct:subject`, which now also allows for textual values, I guess that `dcat:theme` with relaxed range, but still requiring it to be an object property, can still be seen as a restriction on `dct:subject`, effectively making it the same as the 'old' (pre-relaxation) `dct:subject`. Right?

**Comment by rajaram5** [comment]
@dr-shorthair yes, it could work for our use cases if `dcat:theme` is an `object property`

**Comment by rajaram5** [comment]
@makxdekkers I see your point. As I mentioned early in biomedical domain we have more `owl` based ontologies and vocabularies. So if you still like to restrict `range` of `dcat:theme` property it would be nice to have list of values like `skos:Concept`, `owl:Class`.
