### ISSUE TITLE
Chapter on DCAT profiles for DCAT document

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#148]
We need a placeholder regarding DCAT profiles for the document. 
Related to #147 #72 #73 #75

**Comment by dr-shorthair** [comment]
Also conneg? #74

**Comment by davebrowning** [comment]
This looks to have been addressed (in that it was done at the time, but we moved away from saying very much more than 2014 did since it created too many dependencies with other deliverables.)

Since the placeholder was actioned, I propose closing this.  If there is a need for future work to say more, then we should track with a new issue.
