### ISSUE TITLE
Non-English labels and comments

### ISSUE THREAD

**Issue by akuckartz** [w3c/dxwg#174]
DCAT 1.0 contains labels and comments in several languages. I suggest to add at least German translations. I can help with that.

**Comment by riccardoAlbertoni** [comment]
In case it is needed, I am available helping with the Italian translation.

**Comment by dr-shorthair** [comment]
I made some dodgy changes to French and Spanish in #171 which will need checking, so need some volunteers. @agbeltran for Spanish? Looks like all our Belgians are Flemish, but maybe they can help with French. 

@cburle should contribute Portuguese. 
@aisaac and @makxdekkers @lvdbrink Dutch?

We also have Japanese, Greek and Arabic to be checked and updated. 

However, these should probably be deferred to close to the end when English wording is finalized.

**Comment by makxdekkers** [comment]
I guess @aisaac would be the best person to look at the French translations. As to the Dutch translation, it may well be that this isn't necessary, as most Dutch people in the audience will have no problem understanding the English version.

**Comment by makxdekkers** [comment]
Apologies to our Flemish participants. That should have read "Dutch-speaking people".

**Comment by philarcher** [comment]
I had a conversation with a Swedish developer not so long ago and asked about this. Like the Dutch-speaking world, one can safely assume that 99% of Swedish developers are effectively bilingual and therefore have no problem reading English language labels. *However* seeing a label in Swedish (or Dutch) says "this is for you, we want you to use this." It is appreciated; it's like holding a door open for someone who is, of course, perfectly capable of opening it themselves.

I remember the F2F meeting that the GLD WG had at Croke Park, Dublin, when we asked who was able to offer localised labels. It was because of who was in the room and who we knew that we got the eclectic mix of languages you see (Fadi Maali provided the Arabic and I think it was PwC's Nikos Loutas who provided the Greek). Isn't it cool to see Arabic, Greek and Japanese in the same file alongside Italian, French and German? The Japanese came from someone there who does a lot of translations of W3C docs. It was that experience that taught me to always argue against property and class names that differ only in the case of the first letter (like dcat:distribution and dcat:Distribution) - the distinction is meaningless in many languages like Japanese.

**Comment by agbeltran** [comment]
I agree that having as many languages as possible makes it more welcoming for people. I can certainly do/check the Spanish translations.

**Comment by davebrowning** [comment]
Looking roughly at the scale of changes to non-English text in `dcat.ttl`:

- obviously new properties/classes only have recently minted Spanish/Italian etc as well as the English

- a significant proportion of the  properties and classes persisted from DCAT 2014 have had some kind of change in comment or scopenote text - enough to warrant a change to the translation.  [Less than half, but more than a third, depending on how its counted.]

This raises the question of what we do for persisted non-English text where the WG doesn't have skills.  We could just remove them (no chance of ambiguity, consistency with the definitive document) or we could rely on the disclaimer that the published recommendation is the normative text and takes priority.

Personally, I'm inclined to reducing the ambiguity - interested in views of others.

**Comment by philarcher** [comment]
I had a feeling this might come up. I t would be a shame to see all the translations disappear as the DCAT ttl file is a prime example of the Unicode-monger's art (although my browser shows a bit of a mess right now, it used not to :-( From memory, the translators were:

Fadi Maali (Arabic)
Nikos Loutas (Greek)
Giorgia Lodi (Italian)
Christophe Guéret (French)
Boris Villazón-Terrazas (Spanish)

But memory is fallible and may be wrong on all those. My guess is that at least some of them might be willing to lend a hand again.

**Comment by lvdbrink** [comment]
>  @lvdbrink Dutch?
Sure, I could do the Dutch if needed!

**Comment by riccardoAlbertoni** [comment]
PR #1035  completed the Italian translation.

**Comment by davebrowning** [comment]
There's certainly more work that can be done to the dcat.ttl (and equivalent) files.  Since that file is informative and the translations are essentially editorial in nature, it can hopefully be done during CR phase.

**Comment by riccardoAlbertoni** [comment]
I have already done my assignment on this providing Italian translation, so I have removed myself from the assignees.

@akuckartz If you are available for providing the German translation, please prepare a Pull Request. Merging a single new language shouldn't be problematic.

At the moment, besides English, we have Italian, Spanish, and Czech translations in place. I wonder if, at this stage of the process, we have the time for asking and manage the flow of other translations.  I think we better focus on other issues and move this in the future-work.
Any thought/objection especially from other dcat editors?

**Comment by andrea-perego** [comment]
Because of time constraints, I suggest we move this to future work.

**Comment by akuckartz** [comment]
@riccardoAlbertoni I will try to do that until next week.

**Comment by riccardoAlbertoni** [comment]
@andrea-perego : Yes let's move it on future work. In case @akuckartz is providing the german tranlsation, we can keep his PR ready for merging, and merge it as soon as the process constraints allow it.

**Comment by andrea-perego** [comment]
Done.

**Comment by riccardoAlbertoni** [comment]
A Danish translation has been proposed via #1264

**Comment by andrea-perego** [comment]
I don't think there's any need to keep this issue open - translations have been contributed and integrated.

I propose to close it.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
