### ISSUE TITLE
There is a need to distinguish between distributions that package the entire dataset and those that support access to specific items, queries, and packaged downloads of data. [ID51] (5.51)

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#267]
Entered from Google Doc

**Comment by aisaac** [comment]
This is not yet approved as of today, see ACTION 243 on Roba to work out (with Antoine) what #267 means. https://www.w3.org/2018/10/25-dxwg-minutes

**Comment by rob-metalinkage** [comment]
in UCR at https://w3c.github.io/dxwg/ucr/#RDIC

**Comment by makxdekkers** [comment]
Isn't a "_distribution that support access to specific items, queries [etc.]_" in effect a service? As far as I understand it, the updated definition of `dcat:Distribution` in the latest draft seems to imply it represents a file; the definition includes "_Examples of distributions include a CSV file, a netCDF file, or a data-cube_". We added the `dcat:Service` for things that are not files, which seems to be what this issue is about.

**Comment by makxdekkers** [comment]
Based on discussion at https://www.w3.org/2019/02/05-dxwgdcat-minutes, I will draft a proposal that situations that are more complex than access to a 'file' should be modelled as `dcat:Service`.

**Comment by makxdekkers** [comment]
I think the first Note under https://w3c.github.io/dxwg/dcat/#Class:Distribution says it all, so I don't see a need to reformulate that.

**Comment by nicholascar** [comment]
Closing after discussion in Conneg meeting
