### ISSUE TITLE
Location of related work

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#366]
This issue was created in the [Profile Guidance document](https://w3c.github.io/dxwg/profiles/) and is listed in it. Once consensus on addressing it is reached here in comments below, the results will be added to the document and the issue closed.

(Antoine:) This section was recommended here in https://github.com/w3c/dxwg/issues/242#issuecomment-408916364. I now have doubts about the it, as it breaks the flow between two crucial (normative) sections on DXWG recommendations. As an alternative, I suggest to try to fit this in (a subsection of) the introduction if it can be short enough. Otherwise we could put it as appendix and refer to it from the introduction.

**Comment by kcoyle** [comment]
Suggests moving related work from body of document to the introduction.

A short treatment of this topic in the introduction could be amplified (if desired) by a separate analysis document or an appendix to the profgui document. There is definitely a certain history of profiles that could help readers understand the context of this work; I'm not sure how far we want to go with that, however. I'm mainly interested in giving readers an idea of the breadth of the topic by showing different styles of profiles and different purposes rather than attempting an extensive discussion of existing profiles.

**Comment by aisaac** [comment]
@kcoyle had put a note which I think relates to the issue:

> I had thought of this as showing examples of TYPES of profiles. There are profiles like DCAT that take place within a community, make primary use of a base metadata schema, but add or remove based on local need. There are profiles like ODRL that have a very formal meaning (legal license) and are in essence cumulative, with the base standard elements assumed and specific rules for over-riding. There are profiles that use only the namespace of the base profile, but are defined subsets (BIBFRA.ME, but any other example of this would be fine - that's the one I know). And then we could perhaps find a profile that has no strong base profile (ADMS perhaps?) but combines elements as needed from a variety of sources and is independent of any existing vocabulary. The idea would be to show a range of profile motivations, designs, and community involvement.

**Comment by aisaac** [comment]
@agreiner 's comment in #419 is very much related to this issue.

**Comment by rob-metalinkage** [comment]
Its a very long document if we start reviewing all the cases where some sort of profile might be implied through recommendations to reuse vocabularies.  This is why we must stick to process and address requirements introduced via Use Cases.

What is relevant here is that some profiles are (sometimes partially) described using constraints languages, and there are a range of such languages.

If we take "specification" as the intention of dct:Standard, then under for example OpenGeospatial Consoritium model, the "conformance target" must be identified and a set of testable requirements identified. (constraints languages introduce the "testable" aspect.

As an experiment, we can consider documenting any of these vocabulary reuse scenarios as profiles if we can identify a testable requirement.  If its merely "should use terms from X" i think these cases fall outside our definition of profile - its not a constraint.

**Comment by kcoyle** [comment]
I don't believe we yet have an issue for the section "What is a profile?" and the types that I was suggesting are illustrations of types. I'll open an issue for "what is a profile?".

**Comment by aisaac** [comment]
@rob-metalinkage I'm  a bit confused by your comments. Yes we shouldn't try to document things that are not profiles in our sense. But we should certainly have examples, and I can already be sure that some of the examples in the current list will qualify with whatever we end up defining to be profiles (especially the ODRL case).

As @kcoyle hints the issue here is mostly editorial. I.e. what we should do with the current section 4. There's a proposal to deal with these examples in a hopefully useful and rather short way at #419 . Would this be ok?

**Comment by aisaac** [comment]
Considering the reactions on #419 after I pointed to the discussion here from there, I'm suggest the PR at https://github.com/w3c/dxwg/pull/439 to close the issue.

**Comment by aisaac** [comment]
Closed as @kcoyle has reviewed PR #439 and after positive feedback from @agreiner and @rob-metalinkage in #419 . Thanks!
