### ISSUE TITLE
Seek a second profiles implementation

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#409]
This issue was created in the [Profiles Ontology document](https://w3c.github.io/dxwg/profilesont/) and is listed in it. Once consensus on addressing it is reached here in comments below, the results will be added to the document and the issue closed.

**Comment by rob-metalinkage** [comment]
I intend to describe a set of OGC specification interrelationships with the profiles ontology, and implement Linked Data publishing of these using conneg-by-profile.

**Comment by nicholascar** [comment]
Closing as this is part of normal spec work that is underway

**Comment by nicholascar** [comment]
Marled due-for-closing since this is part of the main Rec work and doesn't need a GitHub issue per se.

**Comment by aisaac** [comment]
If there's no second implementation for the current spec and we're still going for CR then we'll have to find one and then probably to create an action for it. But then indeed it could be an action. That said it could also be represented/discussed in a github issue. Considering the timing and the current WG apparent preference for targeting CR, I would think that it's more economical to just leave this issue open instead of re-opening a new one in three weeks. But well, this is purely procedural and I can live with this issue being closed if editors prefer so.

**Comment by nicholascar** [comment]
I prefer to close, just to ensure the cycle of opening & closing is seen to be moving.

Closing after listing in plenary [2019-09-03](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.09.03) + 3-day wait period.

**Comment by kcoyle** [comment]
We could turn this into an action in the tracker if you think it still needs to be tracked.

**Comment by nicholascar** [comment]
@kcoyle yes, I think an ACTION is better.

**Comment by kcoyle** [comment]
Done. ACTION-366
