### ISSUE TITLE
Examples in profile guidance

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#419]
I think the examples should come last, as indicated in section 6. A few could be mentioned in the intro for context, but it seems odd to jump into describing specific ones before we've offered guidance.

**Comment by kcoyle** [comment]
To clarify, by examples are you referring to the ones in section 4 Related Work?

**Comment by agreiner** [comment]
yes

**Comment by aisaac** [comment]
Thanks @agreiner for the comment! And @kcoyle for clarifying. 
Am I right in understanding that this issue is then very close to #366 , as @kcoyle said there that in her mind the 'related work' in section 4 was mostly about giving examples? If yes I'm going to do a cross-reference (and not add a mention of this issue in the doc itself)

Also, in this case I could propose to elaborate on @kcoyle 's suggestion in #366 whereby she suggest to move these 'related work examples' in the introduction. 
I think we won't be able to put a fully fledged description of the examples in the introduction. But what we could do is to have a *brief* description of the 'related work examples' in the intro. We could then compensate for this shortness by coming back to these examples in sections 6 or 7, i.e. as examples of using ProfDesc to create descriptions of profiles and examples of our recommendations being implemented in the wild (even if these implementations are pre-existing to our recommendations, they could still be relevant as examples).

Would this be ok?

**Comment by agreiner** [comment]
sounds good to me! Thanks.

**Comment by rob-metalinkage** [comment]
+1

**Comment by aisaac** [comment]
Considering the reactions on here after cross-linked from #366 , I'm suggest the PR at https://github.com/w3c/dxwg/pull/439 to close the issue.

**Comment by aisaac** [comment]
Closed as @kcoyle has reviewed PR #439 and after positive feedback from @agreiner and @rob-metalinkage . Thanks!
