### ISSUE TITLE
Profiles overview diagram

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#420]
I'm not sure that we need to consider that whole conceptual model all the way up to 
"formalism". Can profiles be based on specifications, not just standards?
I would like the diagram to show bits of multiple specifications used and narrowed by one profile.

**Comment by kcoyle** [comment]
I have to say that the diagram does not say much to me, and I agree that the "formalism" part is, albeit useful, not required. Here's the diagram that Dublin Core uses, which is much more conceptual, although it needs updating:
![singapore-framework](https://user-images.githubusercontent.com/1564129/46130477-b7f4d380-c239-11e8-932b-d928101095ef.png)

The reason I say it needs updating is that it uses terminology from the [Dublin Core Abstract Model](http://dublincore.org/documents/abstract-model/), which, while an interesting model, has not gained traction and is fairly hard to explain.

**Comment by aisaac** [comment]
@agreiner thanks for the comment! I'm a bit confused when you mention "the diagram". Are you refering to a specific place in https://w3c.github.io/dxwg/profiles/? This way we could make the connection in the doc to this issue, and start working on it making sure that we're capturing all that you have in mind :-)

**Comment by agreiner** [comment]
Hm, I don't see it now. There was a diagram in there with four boxes, one each for "formalism", "specifications", "standards", and "profiles".

**Comment by aisaac** [comment]
I understand, it is because the ticket was created just before the new structured replace the old one. The diagram you've seen is not there anymore. It was debatable as you say, if just because the terms and definitions themselves needed to be tackled first (see #371 ) 

There is a plan to add a diagram, possibly at https://w3c.github.io/dxwg/profiles/#publication (where it is mentioned) or earlier in the doc. I could reflect the note to indicate that I was thinking of any of the options for 'models' listed at https://www.w3.org/2017/dxwg/wiki/ProfileRoundup. 

@kcoyle btw if you think there could be something inspired from the Singapore framework added to the listing on the roundup wiki page, I have no objection at all!

In the meantime @agreiner as there is no diagram to complain about yet, is it ok if I close this issue?

**Comment by agreiner** [comment]
sure, I guess we can close this one.

**Comment by aisaac** [comment]
Thanks!

**Comment by nicholascar** [comment]
Just confirming that indeed the diagram was removed with the document restructure after this issue was lodged.
