### ISSUE TITLE
Unintended inference through foaf:primaryTopic to relate Resource to CatalogRecord 

### ISSUE THREAD

**Issue by arminhaller** [w3c/dxwg#438]
The foaf:primaryTopic relation between a Resource and a CatalogRecord does need a revision as it infers a dcat:Resource to be a foaf:Document. Since DataServices are subclasses of a dcat:Resourse, a DataService would be inferred to be a Document, a unintended inference, I believe. A new relation, e.g. dcat:resource or dcat:hasResource would solve that issue.

**Comment by agbeltran** [comment]
+1, and I think it would apply to dcat:Dataset too, as it shouldn't be inferred as a foaf:Document IMO (just a note that the directionality is dcat:CatalogRecord -- foaf:primaryTopic---> dcat:Resource)

**Comment by danbri** [comment]
fwiw the definition of foaf: Document clearly covers datasets. Services in
the abstract  are less plausible, although maybe their homepages, REST
endpoints etc?

**Comment by makxdekkers** [comment]
This sounds like a serious problem. One way to avoid the inference is to use a different property to link `dcat:CatalogRecord` to `dcat:Resource`, for example `dct:subject`, or a new property `dcat:describes`, while keepìng` foaf:primaryTopic` strictly to link to `dcat:Dataset`.

**Comment by agbeltran** [comment]
Thanks @danbri for clarifying (it wasn't too clear for me that datasets are included when looking at the [definition](http://xmlns.com/foaf/spec/)"The Document class represents those things which are, broadly conceived, 'documents'. " and considering ```foaf:Image``` as a subclass)

Considering the issue again, the [spec](https://w3c.github.io/dxwg/dcat/#Property:record_primary_topic) relates the ```dcat:CatalogRecord``` of a ```dcat:Resource``` with its ```foaf:primaryTopic``` (a dataset or a service) and thus implying that the ```dcat:CatalogRecord``` is a ```foaf:Document```, which is correct. 

Thus, it is actually not implying that a ```dcat:Resource``` (and then a ```dcat:DataService```) is a ```foaf:Document```, but the ```dcat:CatalogRecord``` about the ```dcat:Resource``` is the ```foaf:Document```). So, I think there are no problems with what we have now.

We could think of clarifying the [definition](https://w3c.github.io/dxwg/dcat/#Property:record_primary_topic), but I think it is pretty clear actually.  

BTW, I had started checking [```dct:subject```](http://dublincore.org/documents/dcmi-terms/#terms-subject), but it is about the topic of a resource in terms of keywords (ideally from a controlled vocabulary) rather than associating the document with a resource, so wouldn't have helped.

**Comment by dr-shorthair** [comment]
I believe in foaf:Document is intended to be something like 'Representation' - i.e. web page, xml document, record, whatever, and foaf:primaryTopic is intended to point from the representation to the thing that is represents. In classic FOAF that would have been some kind of designator for a person or thing in the world. So this case where it is from the registration record to the thing being registered is a little different. Use of FOAF predicates is a mixed blessing. They are well known, but the semantics are not that tight. But it comes from DCAT 2014 and we would need a very strong case to change it. .

**Comment by makxdekkers** [comment]
So, it seems there is no issue then. The domain foaf:Document is OK as dcat:CatalogRecord is a kind of document, and the range of owl:Thing for dcat:Dataset and dcat:DataService is OK too. Issue can be closed?

**Comment by agbeltran** [comment]
Yes, I believe the issue can be closed. If someone thinks the contrary, please re-open.
