### ISSUE TITLE
Determine which examples of use are to be published in the Profiles Ont doc

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#492]
We have a series of existing profiles modelled using PROF already and we have to decide which of these, and any other examples, get included in the Profiles Ontology Doc (https://w3c.github.io/dxwg/profilesont/). Other examples might be listed elsewhere.

**Comment by kcoyle** [comment]
For the FPWD you might just point to the github folder with examples, or point to the individual examples. For the final document you could have an examples section, or you may decide to create a primer that has the examples if you have many of them. Having a primer would allow you to add any explanation that will help readers understand decisions, options, etc.

**Comment by aisaac** [comment]
+1 for pointing for the folder for the moment.

A Primer sounds a good idea but it adds another document that has "explanation that will help readers understand decisions, options, etc." - both Ontology and Guidance documents may have this...
Actually I'd make a bold suggestion: if the Prof model is not much different from the Guidance model (which we all hope will be the case) and if the number of examples is no bigger than what is envisioned at https://w3c.github.io/dxwg/profiles/#examples, then we could try to have the Prof examples in the Guidance document. 

This creates more dependencies in case the Prof ontology is updated in the future. But:
- it may save us a lot of editorial work overal, now and in the future, because of avoiding redundancies on motivations/principles/etc
- I believe that every time the Prof document(s) would have to be updated in the future, anyway there will probably be the need to update some part of the Guidance doc too.

I guess we don't need to agree on this yet, but I want to use this as an extra argument for saving time on editorial work to fit the examples in the Profile Ontology document now, and merely pointing to the folder.

**Comment by nicholascar** [comment]
Very happy to work Prof Ont examples into the Guidance doc. We have many of the Guidance examples listed just with headings already modelled so I will tidy those up and PR them into Guidance. Perhaps then there will still be a need for snippets and one full example in the Ont doc (I’m just uncomfortable about having none!) but the majority of examples that keep the Guidance and Ont in sync will be in the Guidance doc.

**Comment by nicholascar** [comment]
Two examples now in ProfOnt doc: a basic profile described and a small hierarchy. Likely there will be one or two more examples to demo all parts of the ontology. When complete there, we will be more easily able to decide what examples the Guidance doc might benefit from.

E.g. in the Prof Ont doc all in words, diagrams & RDF.

**Comment by nicholascar** [comment]
Examples to be delt with case-by-case

**Comment by nicholascar** [comment]
General examples now in doc:
* [Initial example](https://w3c.github.io/dxwg/profilesont/#example-1-a-full-example-described-using-the-profiles-vocabulary-in-rdf-turtle)
* [Property isInheritedFrom in use](https://w3c.github.io/dxwg/profilesont/#example-2-property-isinheritedfrom-in-use) - incorrectly titled in doc, should be "Property isTransitiveProfileOf in use"
* [Property isInheritedFrom in use](https://w3c.github.io/dxwg/profilesont/#example-3-property-isinheritedfrom-in-use)

Specific profile examples:
* [DCAT-AP described using Profile Ontology](https://w3c.github.io/dxwg/profilesont/#example-4-dcat-ap-described-using-profile-ontology-in-rdf-turtle)
* [The GeoDCAT-AP profile hierarchy](https://w3c.github.io/dxwg/profilesont/#example-5-the-geodcat-ap-profile-hierarchy-described-using-profile-ontology-in-rdf-turtle)
* [The GeoDCAT-AP profile hierarchy described using Profile Ontology](https://w3c.github.io/dxwg/profilesont/#example-6-the-geodcat-ap-profile-hierarchy-described-using-profile-ontology-in-rdf-turtle) - incorrectly titled, should be "CSIRO Dummy DCAP Profile characterised using PROF"
* [GA Profile of ISO19115 according to PROF in RDF](https://w3c.github.io/dxwg/profilesont/#example-7-ga-profile-of-iso19115-according-to-prof-in-rdf-turtle)
* [ADMS profile of DCAT according to PROF](https://w3c.github.io/dxwg/profilesont/#example-8-adms-profile-of-dcat-according-to-prof-in-rdf-turtle)

The two titling errors noted above, and some example ID tidying, are addressed in PR #1047.

**Comment by nicholascar** [comment]
Closing after listing in plenary [2019-09-03](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.09.03) + 3-day wait period.

**Comment by kcoyle** [comment]
Check with @aisaac if his comment has been satisfied.

**Comment by aisaac** [comment]
@kcoyle it's fine. Ideally these examples should be in the Profile Guidance (or they should at least be mirrored in it, somehow) but as the work on it has been delayed, I believe that the coming version of PROF must have them in.

Note that this is not a formal agreement about the content of these examples (which I've not checked), and I may still argue later for moving the examples. But that can be done in another issue. Anyway the goal of this issue here was rather editorial: determine what examples should go in the document. And I think @nicholascar 's [comment](https://github.com/w3c/dxwg/issues/492#issuecomment-526133792) is good enough.

**Comment by kcoyle** [comment]
I can live with keeping these examples in the document now, but I think that some of them are examples of properties and features that are not fully decided. That makes this a bit of a "chicken and egg" situation, and I will also say (as @aisaac does) that this is not agreement on the content of the examples.

**Comment by nicholascar** [comment]
@kcoyle agreed: not agreement of content, just agreement to, as per title, "Determine which examples are to be published...".

So... still like to close!

**Comment by kcoyle** [comment]
Examples as listed in [comment](https://github.com/w3c/dxwg/issues/492#issuecomment-526133792) are now in [Section 10](https://w3c.github.io/dxwg/profilesont/#examples) of the editor's draft.
