### ISSUE TITLE
Map get resource by profile preferencing from abstract to HTTP & QSA

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#591]
Ensure that the mechanisms described for `get resource by profile` that allow for profile preferencing are equivalent. Is an ordered list (the QSA approach) as rich as the HTTP method that uses both a list an quality ('q') values? Does the Abstract Model function capture all the possibilities of the HTTP realization?

**Comment by aisaac** [comment]
Note from my comments at #575 : There's an issue with Abstract Model for preferences (6.2 and 7.1). 6.2.2 mentions that preferences are expressed in 'some form of list ordering'. This is a bit different from the quality indicators from 7.1.2. And (a question real question at the same time as a possible example of issue:) can q values have ties?

**Comment by larsgsvensson** [comment]
@aisaac scripsit:
> can q values have ties?

Yes, I think they can. The client is free to submit the same q-values for several formats/profiles/languages and the server can have q-values for formats/profiles/languages, too. Since the server multiplies the clients and the servers q-value for each dimension, it can fairly easily come to ties. At the end of the day, the server returns what it considers the best representation.

**Comment by ghost** [comment]
Addressed by addressing https://github.com/w3c/dxwg/issues/575
