### ISSUE TITLE
Do we need to say anything specific about URLs

### ISSUE THREAD

**Issue by pwin** [w3c/dxwg#592]
Throughout the conneg-by-ap document the term URI is used, but there is the specific situation of QSA where the GET request uses a URL with query string arguments.  In practice (rather than in the standard) there are length constraints in both servers and browsers for URLs and a request with a URL exceeding what a server could handle returns a 414 error code.  See https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers for a lengthy discussion on this.  

Essentially, if we are going to propose any QSA approach to content negotiation by profile then we would need to urge caution on length of the querystring.

**Comment by rob-metalinkage** [comment]
@pwin please review the discussion about tokens and issue #290 which should address these concerns.

**Comment by rob-metalinkage** [comment]
@larsgsvensson to add statement about URL length - propose it here. In practice tokens are available which makes this unlikely to be an issue, and identifiers probably are not going to be long complex URLs with their own query parameters (thats bad identifier design)

**Comment by larsgsvensson** [comment]
I propose the following text to be added to [§7.2](https://w3c.github.io/dxwg/conneg-by-ap/#qsa) right before the subsection "Key Naming" (possibly as a note):
> NOTE: 
Since Query String Arguments use URIs (or URLs) to convey important information, implementers should ensure that the total length of the URL does not exceed possible length restrictions. [RFC 7230 §3.1.1](https://tools.ietf.org/html/rfc7230#section-3.1.1) [[RFC 7230]] recommends that senders and recipients support request lines of at least 8,000 octets. Some client and server implementations, however, cannot accept URLs longer than 2.000 characters and e. g. the Sitemap protocol has a length limit of 2.048 characters in a URL. Cf. https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers for a longer discussion of issues related to URL length.

@pwin, is this OK for you?

ACTION-315 (checking if the sysbot picks this up...)

**Comment by pwin** [comment]
yes it is spot on!  thanks @larsgsvensson

**Comment by rob-metalinkage** [comment]
+1

**Comment by larsgsvensson** [comment]
OK, thanks @pwin. Addressed in PR #874.
Preview at https://raw.githack.com/w3c/dxwg/larsgsvensson-qsa-url-length/conneg-by-ap/index.html#qsa

**Comment by larsgsvensson** [comment]
PR is merged, so we can probably close now.
ACTION-315
