### ISSUE TITLE
Text corresponding to dct:conformsTo for dcat:Distribution should be specific 

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#621]
In the current ED, when describing each of the classes, we are usually listing explicitly only the properties not inherited from the superclass. For example, for [Dataset](https://w3c.github.io/dxwg/dcat/#Class:Dataset) we explicitly list under that section the properties defined only for Dataset:  distribution, frequency, spatial/geographic coverage, temporal coverage, was generated by

The only exception is for [Distribution](https://w3c.github.io/dxwg/dcat/#Class:Distribution) that also lists in subsections some of the inherited properties (e.g. title, description, etc). 

We should follow the same approach, and remove the subsections for inherited properties of Distributions

**Comment by dr-shorthair** [comment]
1. I don't quite understand what you are saying here @agbeltran - `dcat:Distribution` has no super-classes, so there are no inherited properties. 

2. OTOH - I recently spotted that – following UML – the two _diagrams_ fail to show the inherited _associations_, only showing inherited class _attributes_. I could probably add all the associations in as attributes as well, so that the class boxes show all the 'recommended' properties inside.

**Comment by agbeltran** [comment]
You are right @dr-shorthair - I was checking the list of properties and thought that dcat:Distribution was inheriting some of them. I will change the purpose of this issue to specialise the text of dct:conformsTo in the dcat:Distribution section.
