### ISSUE TITLE
Deleting closed issues from the DCAT document

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#633]
I have noticed some closed issues are still included in the DCAT document, though they have been closed. (i.e., #68, #53, #431, #114, #128) 

shall we remove them?

**Comment by davebrowning** [comment]
Good idea.  But we need to be check that they are recorded in [Appendix E](https://w3c.github.io/dxwg/dcat/#changes) appropriately.  So I'd expect #68 and #53 to be noted in Appendix E since they are differences to the 2014 spec driven by requirements.  #431 is an issue in one of our WDs so references to it can just be deleted now it has been resolved.  #114 looks a bit more complicated (reading on small UI device and its a long thread - would have to check what DCAT 2014 actually said against what we say now)

**Comment by riccardoAlbertoni** [comment]
I am going  to prepare a new pull for 
- deleting  #431  

and completing the existing pull  
- adding  #68 and #53 in appendix E,

I leave for a more informed contributor the #114 ;)

**Comment by riccardoAlbertoni** [comment]
@davebrowning:
as far as I am concerned the pulls #634 and #635 tidy up the closed issues #431, #68, #53  and can be merged.
Cheers

**Comment by davebrowning** [comment]
Thanks @riccardoAlbertoni - that's great, both merged.  Suggest we leave this open till we have a chance to look at #114

**Comment by davebrowning** [comment]
#114 now addressed by #645, and merged
