### ISSUE TITLE
Inclusion of POST and PUT methods in content negotiation

### ISSUE THREAD

**Issue by kamhayfung** [w3c/dxwg#678]
In 7.1.1.2 (https://www.w3.org/TR/dx-prof-conneg/#listprofilehttplink), a limitation of retrieving the link via the HTTP GET or HEAD method is that a client has no way to discover the profile of the content returned by other methods like POST and PUT. The only other way the client can find that out is through the HTTP OPTIONS method. 

More generally, the document might need better guidance for supporting POST and PUT methods. That's because the profile for the HTTP request bodies for these methods can be different from the profiles for their responses.

**Comment by nicholascar** [comment]
The Server may communicate what profiles it accepts for input (PUT/POST) by setting an Accept-Profile header in response to a HEAD request.

**Comment by larsgsvensson** [comment]
Part of https://www.w3.org/2017/dxwg/track/actions/303

**Comment by nicholascar** [comment]
The Client may then indicate the profile it is using to PUT/POST with by setting the Content-Profile header.

**Comment by larsgsvensson** [comment]
@kamhayfung I'm not entirely sure that this write-up addresses your concern but this is how I think about this.

From what I've understood there are two sides of this.
1. When a client pushes content to a resource on a server using PUT or POST there is no contract as to what the server will return.
2. The client does not know what profiles a server accepts for a given resource.lined out

For 1., my view is that the profile(s) of the content a server returns from a request are the same ones as those listed in the `Content-Profile` header field(s) returned from a HEAD request. So if a client wants to know what profiles _any_ kind of representation returned from a resource (be the verb GET, POST, PUT or PATCH) it can issue a HEAD request and it will know. This is (IMHO) only relevant for successful request, i. e. those that return a 2xx status code, more specifically 200, 201, 202 or 203, since 204 and 205 do not have message bodies.

For 2., my idea was that the server can issue an `Accept-Profile` header field to indicate which profiles it's willing to accept when a client issues a PUT, POST or PATCH request against a resource. In this respect it's similar to the [`Accept-Post` header field](https://www.w3.org/TR/ldp/#header-accept-post) and [`Accept-Patch`](https://tools.ietf.org/html/rfc5789#section-3.1) specifying which media types a given resource on a server is capable of processing. This header field can be returned in _all_ kinds of requests (HEAD, GET, PUT, etc.) for that resource.

If that is **not** what you mean, you can stop reading here, else here is my proposed text (to be introduced _after_ the current example "Using a Link-header to point to a list of available profiles".

============= Begin text ==================

If a server accepts a client to push content to a resource using HTTP PUT, POST or PATCH it can signal which content profiles it can handle by including an `Accept-Profile` header field in _every response_ to a request for that resource. The server can combine this with an `Accept-Post` [LDP] and/or `Accept-Patch` [RFC 5789] header field to signal which media types it's willing to accept.
There can be cases in which a server only supports specific combinations of media types and profiles for the same resource (e. g. content in RDF media types such as `text/turle` or `application/rdf+xml` is available in the profiles `urn:example:profile1` and `urn:example:profile2` whereas content in `application/marc` and `application/marcxml+xml` is available in the profile `urn:example:profile3`). In this case the server SHOULD examine the `Accept`-header sent by the client in order to determine which is the media type preferred by the client and include the corresponding profile URI(s) in its `Accept-Profile` header.

Example:
\# Client asks server which profiles it accepts for a resource
HEAD /a/resource HTTP/1.1
Accept: application/xml

--------------

\# Server answers which media types and profiles it can accept
HTTP/1.1 200 OK
Content-Type: application/xml
Accept-Post: application/xml
Accept-Profile: urn:example:profile1

--------------

\# Client POSTs content
POST /a/resource HTTP/1.1
Accept: application/xml
Content-Type: application/xml;encoding=UTF-8
Content-Length: 1234
Content-Profile: urn:example:profile1

\<lorem>\<ipsum>dolor sit ... \</ipsum>\</lorem>

-------------------

\# Server responds that the resource was created at /a/resource#comment-12345
HTTP/1.1 201 Created
Location: /a/resource#comment-12345
Content-Type: application/xml;charset=UTF-8
Content-Profile: urn:example:1
\# and includes the acceptable media-types and profiles again
Accept-Profile: urn:example:1
Accept-Post: application/xml;charset=UTF-8

============= End text ==================

Is this the right direction?

@RubenVerborgh, do you have strong views on this?

**Comment by kamhayfung** [comment]
@larsgsvensson , `HEAD` header is intended to fetch a response from a server identical to a `GET` response except the body part. `Accept-*` headers will sound a bit odd in a `GET` response to a `GET` request which does not have a message body.
 
When your `HEAD` approach is applied to a RESTful service, the result will get interesting. Before a client creates resource 123 in the server, it can interrogate the server about the profile(s) it supports using `HEAD`:
 
```
HEAD /a/resources/123 HTTP/1.1
Accept: application/xml
```
 
Since resource 123 does not yet exist, the server might return a 404 response. In order to tell the client about its supported profile(s), the server also needs to return the `Accept-*` headers:
 
```
HTTP/1.1 404 NOT FOUND
Accept-Post: application/xml
Accept-Profile: urn:example:profile1
```
 
Alternatively, the server could just return the following even when the resource does not exist:

```
HTTP/1.1 200 OK
Content-Type: application/xml
Content-Profile: urn:example:profile1
Accept-Post: application/xml
Accept-Profile: urn:example:profile1
```
 
Are both these options valid?
 
Nevertheless, once the client works out the profiles supported by a server, the rest of your example makes sense.

**Comment by RubenVerborgh** [comment]
> Alternatively, the server could just return the following even when the resource does not exist:
> 
> ```
> HTTP/1.1 200 OK
> ```

No, that should be a 404.

**Comment by nicholascar** [comment]
POST & PUT have been considered out of scope for this. 

We have placed this Issue in the document so we leave it there for comment.

**Comment by larsgsvensson** [comment]
> POST & PUT have been considered out of scope for this.

I remember that we spoke about this in the 2019-08-08 Meeting (and it's in the [minutes](https://www.w3.org/2019/08/08-dxwgcneg-minutes#x07)), but I cannot remember that we decided to close this issue. It's true that we don't have a use case for POST and PUT, but can we really ignore it?

**Comment by larsgsvensson** [comment]
@nicholascar scripsit on [public-dxwg-wg](http://lists.w3.org/Archives/Public/public-dxwg-wg/2019Aug/0147.html):
> We’re not ignoring it: we placed the Issue in the document (for the first time) and put a bit in after is saying that without further motivation it would be closed. So it will be there for all to see for 3PWD release, I like 2PWD for which we forgot to include it.

> Without further motivation though it will be removed for 4PWD or whatever the next release is.

If it is to be reviewed during 3PWD it's not due for closing yet, so I remove that tag.

**Comment by nicholascar** [comment]
@kamhayfung can you please comment on the direction of the comments here?

**Comment by larsgsvensson** [comment]
@kamhayfung since we're moving the work towards CR we'd really appreciate your feedback here

**Comment by larsgsvensson** [comment]
POST & PUT have been considered out of scope for this document.

There will be a note in the document documenting that decision.

The original poster has been pinged twice over the past four weeks and has not responded, so I mark this as due-for-closing again.
