### ISSUE TITLE
Project context [RPCX]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#71]
<section class='requirement' id='RPCX'><h3>Project context [<a href='https://www.w3.org/TR/dcat-ucr#RPCX' target='_blank'>RPCX</a>]</h3><p>Provide a means to define a 'project' as a research, funding or work organzation context of a dataset.</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID49' target='_blank'>Dataset business context [ID49]</a> <a href='https://www.w3.org/TR/dcat-ucr#ID31' target='_blank'>Modeling funding sources [ID31]</a> </section>

**Comment by dr-shorthair** [comment]
I have a draft proposal for a small vocabulary for Project, as a subclass of `prov:Activity`. 
See 
https://dr-shorthair.github.io/ont/project/ 

This would support linking a dataset to a project using the `prov:wasGeneratedBy` predicate, as mentioned in #77

**Comment by andrea-perego** [comment]
Thanks, @dr-shorthair . I would also like to contribute some work we did to map DataCite to DCAT-AP, which includes the mapping of what in DataCite is called "Funding Reference". The mapping tables are here: https://ec-jrc.github.io/datacite-to-dcat-ap/

I think this is also one of the possible use cases for the use of qualified and non-qualified forms.
The non-qualified form is the basic case where you want to say that a given dataset has been created by a given project. However, if you also need to say that this is done in a given timeframe of the activity of a project you need to add a node in the graph, between "project" and "dataset", where to attach this information. 

@dr-shorthair , in my understanding the vocabulary you contributed support both cases, right?

**Comment by dr-shorthair** [comment]
Linking through to funding details is part of the proposed Project ontology. Not sure if I got it all right yet, so would be interested in working through other examples.

**Comment by dr-shorthair** [comment]
Suggest removing the following labels: 
profile, semantics, service, usage_control, version
??

**Comment by dr-shorthair** [comment]
Picking up the [second example on #253](https://github.com/w3c/dxwg/issues/253#issuecomment-403276218) which describes a [dataset from CSIRO's DAP](https://data.csiro.au/dap/landingpage?pid=csiro:P366-2003SEPT), the following uses PROV to document the project context for the dataset.  The `PROV-O` property `prov:wasGeneratedBy` points to `dap:P366` which is a `prov:Activity`, which in turn is associated with `dap:ATNF` and used the `dap:Parkes-radio-telescope`. 

```
dap:atnf-P366-2003SEPT
  rdf:type dcat:Dataset ;
# other properties omitted here
  dcterms:identifier "https://doi.org/10.4225/08/598dc08d07bb7"^^xsd:anyURI ;
  dcterms:relation [      dcterms:identifier "PH0090_0011.sf" ;    ] ;
  dcterms:relation [      dcterms:identifier "PH0090_0021.sf" ;    ] ;
  dcterms:relation [      dcterms:identifier "PH0090_0031.sf" ;    ] ;
  dcterms:title "Parkes observations for project P366 semester 2003SEPT" ;
  dcat:contactPoint dap:MartaBurgay-vcard ;
  dcat:keyword "pulsar" ;
  dcat:landingPage <https://data.csiro.au/dap/landingpage?pid=csiro:P366-2003SEPT> ;
  prov:wasGeneratedBy dap:P366 ;
.
dap:P366
  rdf:type prov:Activity ;
  dcterms:contributor dap:A_Lyne , dap:Andrea_Possenti , dap:B_Joshi , dap:F_Camilo , dap:G_Pearce , dap:M_Kramer , dap:M_McLaughlin , dap:Nichi_D'Amico , dap:R_Manchester ;
  dcterms:type "Observation" ;
  rdfs:comment "Parkes multibeam high-latitude pulsar survey" ;
  rdfs:label "P366 - Parkes multibeam high-latitude pulsar survey" ;
  prov:used dap:Parkes-radio-telescope ;
  prov:wasAssociatedWith dap:Marta_Burgay ;
  prov:wasInformedBy dap:ATNF ;
.
dap:ATNF
  rdf:type prov:Activity ;
  rdfs:label "Australia Telescope National Facility" ;
  prov:informed dap:P366 ;
.
```

Note that `prov:wasGeneratedBy` is axiomatized
```
prov:wasGeneratedBy
  rdf:type owl:ObjectProperty ;
  rdfs:domain prov:Entity ;
  rdfs:range prov:Activity ;
.
```
**so this entails that `dap:atnf-P366-2003SEPT` is a `prov:Entity`.**

**Comment by dr-shorthair** [comment]
... and not being entirely happy with the limitations of PROV and DC, here is the same activity described using my proposed [Project Ontology](https://dr-shorthair.github.io/ont/project/), which **specializes `prov:Activity`** for planned and budgeted activities commonly known as Projects :-)
```
dap:P366-1
  rdf:type prov:Activity ;
  rdfs:comment "Parkes multibeam high-latitude pulsar survey" ;
  rdfs:label "P366 - Parkes multibeam high-latitude pulsar survey" ;
  proj:hasParticipant dap:A_Lyne , dap:Andrea_Possenti , dap:B_Joshi , dap:F_Camilo , dap:G_Pearce , dap:M_Kramer , dap:M_McLaughlin , dap:Nichi_D'Amico, dap:R_Manchester ;
  proj:hasPrincipalInvestigator dap:Marta_Burgay ;
  proj:isSubActivityOf dap:ATNF-1 ;
  proj:objective "Observation" ;
  prov:used dap:Parkes-radio-telescope ;
.
dap:ATNF-1
  rdf:type proj:Project ;
  rdf:type prov:Activity ;
  rdfs:label "Australia Telescope National Facility" ;
  proj:hasSubActivity dap:P366-1 ;
.
```

Also see #77 #76 #128

**Comment by dr-shorthair** [comment]
If this pattern is agreed to be useful, then a key implementation question is
(i) do we recommend the use of properties from [PROV-O](https://www.w3.org/TR/prov-o/) directly, or 
(ii) do we **'clone' the PROV-O properties that we want to use into the `dcat` namespace**, thus avoiding an additional dependency - see #111 

Note that an explicit dependency on PROV brings [entailments](https://www.w3.org/TR/prov-o/) and [constraints](https://www.w3.org/TR/prov-constraints/), the consequences of which might not be clear. 

If the cloning route is taken then we should include alignment axioms like 

`dcat:wasGeneratedBy owl:equivalentProperty prov:wasGeneratedBy .`

in the [DCAT-PROV alignment graph](https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/prov.ttl).

**Comment by dr-shorthair** [comment]
Proposal:

1. Add property `dcat:wasGeneratedBy` for use on `dcat:Dataset`. It should be an `owl:ObjectProperty` whose target SHOULD be an activity or project; 
2. Add a non-normative note pointing to `prov:Activity` as a useful formalization for activities that generate datasets, and include an [example similar to above](https://github.com/w3c/dxwg/issues/71#issuecomment-404059767) to illustrate its use  ; 
3. In the DCAT-PROV alignment include the axiom 
```
dcat:wasGeneratedBy owl:equivalentProperty prov:wasGeneratedBy .
```
so that PROV enthusiasts can dive right in; 
4. Publish the [Project Ontology](https://dr-shorthair.github.io/ont/project/) as a working group Note ;-) ; 
5. Add a non-normative note pointing to `proj:Project` as a useful formalization for planned activities that generate datasets, and include an [example similar to above](https://github.com/w3c/dxwg/issues/71#issuecomment-404062148) to illustrate its use

**Comment by dr-shorthair** [comment]
@andrea-perego the https://webgate.ec.europa.eu repo you mentioned above is private :-(

**Comment by dr-shorthair** [comment]
See https://ec-jrc.github.io/datacite-to-dcat-ap/#alignment-issues-agent-roles as evidence of independent discovery of this pattern (thanks @andrea-perego

**Comment by dr-shorthair** [comment]
Mostly resolved by #312 

The remaining issue is whether to on the proposed [Project Vocabulary](https://dr-shorthair.github.io/ont/project/) as an option for project descriptions - specializing `prov:Activity`. 

The paragraph at the end of https://w3c.github.io/dxwg/dcat/#Property:dataset_wasgeneratedby mentions several existing project vocabularies, though only DOAP (for software projects) is cleanly documented, and none is linked to prov:Activity

**Comment by pwin** [comment]
Are we going to provide a distinction between 'project' [defined by time, topic, budget, etc] and 'business as usual'  [BAU] for the context of data-related activity?  Both deliver data that will need cataloguing.  The BAU has some characteristics described in the Project Vocabulary  - name, objective, leader, sponsor etc, and also have activity structures, dependency structures,  stakeholders, funding etc.  They just don't operate in a 'project' manner.

**Comment by davebrowning** [comment]
Mmm.  The requirements (particularly [ID49](https://www.w3.org/TR/dcat-ucr/#ID49) talk about business context.  Projects are one kind of context, it seems that examples which show other contexts (such as business as usual)  would be useful and helpful to adopters.  Other kinds of project could also be useful, I guess, but we do need to be a bit careful about too many examples...

**Comment by dr-shorthair** [comment]
I think we can tweak the wording, adding 'business as usual' or 'ongoing activity' to the list of kinds of activities. 

And I think an ongoing-activity can be described as a `prov:Activity` with no `prov:endedAtTime`. 

See https://github.com/w3c/dxwg/pull/338

**Comment by larsgsvensson** [comment]
@dr-shorthair scripsit:
> And I think an ongoing-activity can be described as a `prov:Activity` with no `prov:endedAtTime`.

This is an interesting look at the nature of activities. I always thought that activities need to be completed in order to be recorded in prov... Is there any previous work on this?

**Comment by davebrowning** [comment]
Mmm.  I haven't had a chance to look for something public - not aware of anything off the top of my head.  I would have thought others would have come across this.

If I recall correctly, where my colleagues are using this internally, `prov:Activity` is always bounded (i.e. has a `prov:endedAtTime`).  We took the view that that our feeds are operate continually rather than continuously - a record at a time, so to speak - so the publication activity was quite granular, but finite. (There are weaknesses in this approach, in my view but it suited our specific use case).  The business context on the other hand, isn't finite - rather, it's indefinite, with no known end time.

**Comment by larsgsvensson** [comment]
Our use case (might be slightly OT for this thread) is when a human assigns a language code to a document. Is every assignment its own `prov:Activity` or can we see the continuous assignment of language codes as one `prov:Activity` going on since we started doing that?

**Comment by dr-shorthair** [comment]
In the real world we have 'projects' (or similar ongoing activities), within which there are more specific or atomic activities. The PROV model focuses on the latter - the atomic events associated with each specific output. Nevertheless there appears to be a quite common requirement to _describe_ the bigger (project) context instead of (or in addition to) the atomic events. It's not that the latter don't exist conceptually of course, just that the appropriate level of detail for the application may not necessarily match the viewpoint that guided the development of the PROV model and OWL implementation.

IMO however the prov model still applies at the coarser level - all the properties of a prov:Activity are relevant to projects or ongoing activities. The key addition needed is an activity-nesting or -composition predicate.

**Comment by dr-shorthair** [comment]
So the specific answer to @larsgsvensson is 'both', conceptually at least. But practiclaly it might be the case that you only want to describe the overall process and not each individual sub-activity.

**Comment by dr-shorthair** [comment]
I think we can close this issue. The example

**Comment by dr-shorthair** [comment]
I think we can close this issue. 
Example here https://w3c.github.io/dxwg/dcat/#examples-dataset-provenance
Normative statements here https://w3c.github.io/dxwg/dcat/#Property:dataset_wasgeneratedby
(from #312, #338).

**Comment by dr-shorthair** [comment]
Should we close this issue?  
Example here https://w3c.github.io/dxwg/dcat/#examples-dataset-provenance
Normative statements here https://w3c.github.io/dxwg/dcat/#Property:dataset_wasgeneratedby
(from #312, #338). 

Or do we still intend to look at the [proposed Project Ontology](https://dr-shorthair.github.io/ont/project/) as a potential "Note"

**Comment by davebrowning** [comment]
When we last looked at this I had the impression we could/wanted to do more (for example the continuous publication stuff), but its also true that that we can always do more... I do think we've addressed the requirement, and the other scenarios are tracked by actions [here](https://www.w3.org/2017/dxwg/track/actions/173) and [here](https://www.w3.org/2017/dxwg/track/actions/174).

re: a potential "Note" - I have no strong opinion (though I do think the ontology is useful)

**Comment by dr-shorthair** [comment]
So I put the note on the table more or less from the beginning of the DXWG. 

Everyone who has looked at it seems to agree that it is useful, though it has attracted no formal reaction, positive or negative. I have not pushed it since we were clearly quite busy enough with the other things on our plate. But it could probably be finished up with 2-3 days work. So the question becomes: is there an appetite in the DXWG for another non-Rec-track deliverable? Should I raise a specific issue for this question, so we can decide one way or the other?

**Comment by agbeltran** [comment]
@andrea-perego - I cannot access the link to the mapping that you referred here., is it available somewhere else?

> Thanks, @dr-shorthair . I would also like to contribute some work we did to map DataCite to DCAT-AP, which includes the mapping of what in DataCite is called "Funding Reference". The mapping tables are here: https://webgate.ec.europa.eu/CITnet/stash/projects/ODCKAN/repos/datacite-to-dcat-ap/browse/documentation/Mappings.md
> 
> I think this is also one of the possible use cases for the use of qualified and non-qualified forms.
> The non-qualified form is the basic case where you want to say that a given dataset has been created by a given project. However, if you also need to say that this is done in a given timeframe of the activity of a project you need to add a node in the graph, between "project" and "dataset", where to attach this information.
> 
> @dr-shorthair , in my understanding the vocabulary you contributed support both cases, right?

**Comment by agbeltran** [comment]
> So I put the note on the table more or less from the beginning of the DXWG.
> 
> Everyone who has looked at it seems to agree that it is useful, though it has attracted no formal reaction, positive or negative. I have not pushed it since we were clearly quite busy enough with the other things on our plate. But it could probably be finished up with 2-3 days work. So the question becomes: is there an appetite in the DXWG for another non-Rec-track deliverable? Should I raise a specific issue for this question, so we can decide one way or the other?

Given that projects (and related funding, see #66) are generic topics that go beyond DCAT, I think it is worth considering the Project ontology as another output of the WG, as it can be easily used within DCAT to cover the requirements (this on and #66). Not sure about the process, though, as strictly our purpose is the DCAT revision.

**Comment by agbeltran** [comment]
As this issue needs more discussion, I'm moving it to the next milestone.

**Comment by andrea-perego** [comment]
> @andrea-perego - I cannot access the link to the mapping that you referred here., is it available somewhere else?

Sorry for the late reaction, @agbeltran . The work is now on GH (I just updated the link in the original comment):

https://ec-jrc.github.io/datacite-to-dcat-ap/

**Comment by davebrowning** [comment]
This issue remains active, since there are a number of things we could do with either the [project ontology](https://dr-shorthair.github.io/ont/project/) or in providing additional examples that perhaps go beyond the common meaning of the word project.  This would all be valueable but requires resource which won't be available in 3PWD timescales, so removing from this milestone and 'parking' it in  4PWD for now

**Comment by andrea-perego** [comment]
As there has been no further discussion on this issue, I propose to close it.

**Comment by dr-shorthair** [comment]
Agree
