### ISSUE TITLE
Indicate the UCR doc early in the Ontology doc

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#749]
We have on links to the UCR doc other than in the A.2 Requirements and many reviewers haven't realised we have a UCR doc we're working from. 

We may need to add a link to the **Overview of DXWG documents on profiles** and/or **4. Motivation** as well as referencing individual Requirements in the main text.

**Comment by tombaker** [comment]
It is worth noting that [UCR document](https://w3c.github.io/dxwg/ucr/#introduction) defines its own scope as that of identifying use cases and requirements for the three chartered DXWG deliverables: 1) revising DCAT, 2) publishing guidance on the use of application profiles, and 3) providing guidance on content negotiation.  The document makes no reference to a "profiles vocabulary" or "profiles ontology" as being either a deliverable of the working group or a motivation for the use cases and requirements.

**Comment by rob-metalinkage** [comment]
The charter also states that 

"Subject to its capacity, the working group may choose to develop additional relevant vocabularies in response to community demand."

it also states: "The goal of the working group is to extend the existing DCAT standard in line with wider practice but also to recognize and support diverse approaches to data description and Dataset Exchange more generally."

At the time, it quickly became clear to that the requirements established in the UCR identified a "community demand" that would not be met by the other three deliverables - and given that was the sole "community demand" for implementations that Nick and I were needing to implement (we really dont need DCAT, conneg is useful but not critical and guidance without a working mechanism isnt possible).

The abstract for the UCR clearly states "Further, they motivate the creation of guidelines for and a formalisation of the concept of (application) profiles and how to describe those, and the need for a mechanism to exchange information about those profiles including profile-based content-negotiation."

Given that there is a "mechanism to exchange information about those profiles " now available that has been through public comment and the only substantive unaddressed issues actually appear to be about refining wording and naming so people can see more clearly how to apply it in their familiar cases... is it really helpful to be adding more non-productive work to the process by attempting to revisit matters afresh that were addressed nearly two years ago?  

At any rate this is moot because this issue was addressed in the 2PWD:

"For the purposes of dataset exchange and with the lack of a formal W3C method for describing the objects related to profiles, the DXWG underwent a process of Use Case and Requirements gathering. They established the Dataset Exchange Use Case and Requirements document (the UCR document) [DCAT-UCR] which groups requirements for profiles into the following sections:"

**Comment by rob-metalinkage** [comment]
i have updated the milestones and status to reflect that this issue was dealt with in the 2PWD.

**Comment by tombaker** [comment]
@rob-metalinkage What the charter [actually says](https://www.w3.org/2017/dxwg/charter#deliverables) is that additional vocabularies can be created as "non-normative documents" (i.e., WG Notes):

> Other non-normative documents may be created such as: ... additional relevant vocabularies in response to community demand.

I see no reference in the body of the [UCR Note](https://www.w3.org/TR/dcat-ucr/) to a need for a "formal" vocabulary for describing profiles.  Can you please point me to the relevant section?

> "For the purposes of dataset exchange and with the lack of a formal W3C method for describing the objects related to profiles, the DXWG underwent a process of Use Case and Requirements gathering.

I see no evidence that in undertaking the collection of use cases, the DXWG was motivated by a "lack of a formal W3C method for describing the objects related to profiles".  If I am correct that this was not a significant motivation, then the sentence as formulated above is arguably misleading.

I am surprised by the existence of a ["2PWD" for PROF](https://www.w3.org/TR/2019/WD-dx-prof-20190402/) because I was unaware that the WG had approved its publication.  Can anyone point me to the resolution?

**Comment by rob-metalinkage** [comment]
Feel free to work out how to meet the requirements requirements any other way.  If you do not share or understand the motivation of others thats fine, but coming in late to a process you are probably missing a lot of context of why people have thought this was a worthwhile thing to do.  It was extensively discussed, a range of people have seen fit to comment on it and no one has invalidated its existence by pointing to an existing solution to meet the requirements tagged "profile" in the UCR.

So if you dont need it or get it, that doesnt provide a rationale to deny the motivations of others.

**Comment by makxdekkers** [comment]
@tombaker The 2PWD for PROF was announced on 2 April by Peter & Karen at https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Apr/0048.html.

**Comment by tombaker** [comment]
@rob-metalinkage The [UCR Note](https://www.w3.org/TR/dcat-ucr/) is indeed a fine and valuable piece of work.

However, the "profile" tag used to tag requirements there refers not to PROF, but to the Guidance deliverable.  Indeed, most of the requirements so tagged are quite orthogonal to the content of metadata about profiles.

Please consider that all readers coming to PROF since the publication of the First Public Working Draft just eight months ago are "coming in late" to a process.  W3C process, whereby issues are addressed formally, with resolution texts that explain WG decisions, actually provides an opportunity for a WG to explain its choices and articulate underlying assumptions.  When formal responses to issues link to supporting documentation (meeting minutes, requirements in UCR, and the like), they build up an intellectual audit trail that others can follow to understand the rationale for a specification's design.

For specifications on Rec track, W3C process sets a high bar for working groups to respond to issues and document WG consensus.  WGs are supposed to seek out such comment, which also has the effect of demonstrating interest in a deliverable.  It should by default be assumed that commenters are commenting in good faith.  The burden is on creators of a Rec-track spec to ensure consensus.  The burden does not lie with readers and commenters to "figure out how to meet the requirements any other way", as you suggest above.  

@kcoyle has recently reminded us of the [agreed process for closing issues](https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Aug/0276.html) in the WG.  If you do not agree with this process, PROF could more easily and quickly be published as a WG Note.  Whether the specification were a Recommendation or WG Note would have no impact on its usability.

**Comment by kcoyle** [comment]
The UCR is referenced in a [section of the PROF vocabulary](https://w3c.github.io/dxwg/profilesont/#resource-roles-vocab). It is, to me, a bit vague, as it isn't obvious from the text how those requirements are fulfilled by the vocabulary. It would be more convincing if the text said: "and PROF fulfills this requirement by offering ..." rather than just stating that it does fulfill it but not saying how. Also, the links there are to general headings rather than specific requirements, and not all requirements under those headings may be relevant. Although I am not sure that it belongs in the document itself, a brief analysis showing the exact list of relevant requirements might be good background.

**Comment by tombaker** [comment]
On Mon, Aug 26, 2019 at 02:16:04AM -0700, makxdekkers wrote:
> @tombaker The 2PWD for PROF was announced on 2 April by Peter & Karen at https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Apr/0048.html.

@makxdekkers Thank you for the link, which I had also found.  My point was that there is no record of a WG resolution to publish in any of the meeting minutes. The only invitation to comment, AFAICT, was the one posting you cite, which is world-readable but internal to the working group.
