### ISSUE TITLE
Collecting implementation evidence for DCAT-2

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#767]
I started preparing a spreadsheet to collect implementation evidence, based on the table in the DCAT 2014 implementation report: 

https://www.w3.org/2011/gld/wiki/DCAT_Implementations#Summary_of_terms_usage

You can find it here:

https://docs.google.com/spreadsheets/d/1eEVUuPFAGO2GjS5ocxylY8T1AlpqlwnOTc3er_Mhcv4/edit?usp=sharing

In the spreadsheet I added all the classes now in DCAT-2, along all the properties explicitly or implicitly associated with them. I also marked with a gray background those classes/properties which are a legacy from DCAT 2014 - and for which I guess we don't need to provide implementation evidence. Finally, I used other formatting for specifying the new classes / properties, "recommended" properties, those inherited from `dcat:Resource`, those inherited from parent classes (see the "legenda" tab in the spreadsheet for details).

@dr-shorthair , @agbeltran , @davebrowning , @pwin , do you think this approach could make sense?

**Comment by riccardoAlbertoni** [comment]
see also #680

**Comment by agbeltran** [comment]
This report on DCAT-AP usage (https://joinup.ec.europa.eu/document/report-dcat-ap-use) that @andrea-perego referenced in #728 seems relevant for our implementation report.

**Comment by andrea-perego** [comment]
@agbeltran said:

> This report on DCAT-AP usage (https://joinup.ec.europa.eu/document/report-dcat-ap-use) that @andrea-perego referenced in #728 seems relevant for our implementation report.

Please be aware that I used it in the spreadsheet to report implementation evidence from the European Data Portal.

**Comment by riccardoAlbertoni** [comment]
I suspect this issue is not for the milestone DCAT CR.
The implementation evidence is collected once that we have the Candidate Recommendation. 

That is what I have understood following the discussion during last plenary, and in particular, 
considering what Philippe Le Hégaret said at 21:22:22 in the [plenary minutes](https://www.w3.org/2019/03/12-dxwg-irc): 
>Once you have CR, you have to gather implementation experience. You have three steps, CR, proposal recommendation (at which point we ask members at large to review), and then recommendation.

and also reading the [Candidate rec section](https://www.w3.org/2019/Process-20190301/#candidate-rec) in the  W3C consortium Process Document.

**I might be mistaken, but what is necessary at this stage is to document how adequate implementation experience will be demonstrated by  indicating the way we want to follow in the section Status of this document.**

For example, in the first candidate REC of the  [Data on the Web Best Practices](https://www.w3.org/TR/2016/CR-dwbp-20160830/), the DWBP group wrote:

>The Working Group invites publishers to test whether their datasets pass or fail each of the Best Practices in this document using the DWBP Evidences Form. The information gathered through this means will be augmented by further analysis of data available on the Web and, as noted in the charter, national or sector-specific guidelines that reference the Best Practices. The Working Group expects to adduce the combined set of evidence when requesting that the Director advance this document to Proposed Recommendation.

DWBP developed a dedicate set of forms, but I guess that we might as well prepare a github wiki page where to provide instruction for implementers considering as possible ways one or more among the following possibilities 
- to send the link to  their implementations to the group 
- to compile a wiki page (e.g. https://github.com/w3c/dxwg/wiki/DCAT-implementation-evidence)
- to compile a google form 
- ...
 
The preliminary collection of implementations started by  @andrea-perego  and  @dr-shorthair are in any case useful preparing the CR, they might be precious to identify DCAT features/ terms which might be at risk.  In fact, according to the [Candidate rec section](https://www.w3.org/2019/Process-20190301/#candidate-rec), the Working Group to publish a Candidate Recommendation
>MAY identify features in the document as "at risk". These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.

**Comment by agbeltran** [comment]
@riccardoAlbertoni 

> I suspect this issue is not for the milestone DCAT CR.
> The implementation evidence is collected once that we have the Candidate Recommendation.
> 
> That is what I have understood following the discussion during last plenary, and in particular,
> considering what Philippe Le Hégaret said at 21:22:22 in the [plenary minutes](https://www.w3.org/2019/03/12-dxwg-irc):
> 
> > Once you have CR, you have to gather implementation experience. You have three steps, CR, proposal recommendation (at which point we ask members at large to review), and then recommendation.
> 
> 

Yes, that was my understanding too. This issue had ended up in the CR milestone simply because I renamed the milestone we were using. I have now created a different milestone and moved this issue there. Thanks.

**Comment by pwin** [comment]
https://github.com/pwin/DataPortalAnalysis has some code and results of the classes of subject and object together with numbers of triples for a wide range of predicates.  This can be extended

**Comment by pwin** [comment]
https://docs.google.com/spreadsheets/d/10-UIgM1xLQXNsaSgU6xRsPlsYo3jABreVNwjzciGPKM/edit?usp=sharing is the spreadsheet of  @andrea-perego with dcat:DataDistributionService info removed and preds merged with dcat:DataService

**Comment by andrea-perego** [comment]
For the current version of the implementation report, see PR https://github.com/w3c/dxwg/pull/1138

I think we can close this issue.

**Comment by riccardoAlbertoni** [comment]
yes, let's close this!

**Comment by andrea-perego** [comment]
Done.
