### ISSUE TITLE
ShEx community comment on resource descriptor

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#794]
While it could be useful to have properties to relate these ShEx artifacts to other types of artifact around a profile, we see that these relations are modeled in Profiles Ontology with `hasResource` pointing to a resource descriptor, which in turn has a role (`hasRole`) named by a SKOS concept (in a construct that resembles an RDF type declaration).  Modeling these as properties would more straightforwardly support scenarios in which a given profile-related resource were related to more than one other profile-related resource, but with different roles.  It is on the other hand not clear to us what would be lost by modeling relationships directly with properties.

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Feb/0001.html

**Comment by nicholascar** [comment]
The reason for taking this qualified relations approach (`hasResource/hasRole`) is that there are potentially many `ResourceRole` roles and thus there could be many properties. [Already the vocabulary contains 8 Roles](https://w3c.github.io/dxwg/prof/#resource-roles-vocab) and we hope for and expect more to be created. So it's true that perhaps nothing would be *lost* in using direct properties but, over time, the direct properties, if declared in PROF and thus unchangeable, would bias against the use of future roles for which direct properties were not created, since they were unknown at the time of PROF creation.

If your community feels strongly about direct properties, could an Issue be created for the 4PWD to add them to PROF?

**Comment by nicholascar** [comment]
@tombaker @kcoyle are either of you motivated to carry this issue forward as suggested above ot in other ways? Tom was the original raiser of the Issue.

**Comment by kcoyle** [comment]
@nicholascar As the issue as raised has been rejected, I doubt if there's anything more to say.

**Comment by dr-shorthair** [comment]
The key point is to allow the set of roles to evolve on a different timescale to the ontology. 

The proposed solution is a 'soft-typing' mechanism where an association object is 'tagged' with a value from a (controlled-)vocabulary. Alternatively, the set of roles could be managed as a set of sub-properties of the primary relation. Either could be maintained separately from the main ontology, incl. different namespace(s).

People approaching the requirement from different heritages tend to prefer one or the other, though in the RDF context there is little practical difference between them, particularly as you can define schema-level (t-box) components at run-time (i.e. embedded within the a-box graph).
