### ISSUE TITLE
Related datasets [RRDS]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#81]
<section class='requirement' id='RRDS'><h3>Related datasets [<a href='https://www.w3.org/TR/dcat-ucr#RRDS' target='_blank'>RRDS</a>]</h3><p>Ability to represent the different relationships between datasets, including: versions of a dataset, collection of datasets, to describe their inclusion criteria and to define the 'hasPart'/'partOf' relationship, derivation, e.g. processed data that is derived from raw data</p><p class='note'>this requriement to be rolled in here: Update method of Dataset: Indicate the update method of a Dataset description, e.g. whether each new dataset entirely supercedes previous ones (is stand-alone), or whether there is a base dataset with files that effect updates to that base.</p><br/><em>Related requirements</em>: <a href='https://www.w3.org/TR/dcat-ucr#RID8' target='_blank'/> <a href='https://www.w3.org/TR/dcat-ucr#RPIF' target='_blank'>Provenance information [RPIF]</a> <br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID32' target='_blank'>Relationships between Datasets [ID32]</a> <a href='https://www.w3.org/TR/dcat-ucr#ID47' target='_blank'>Define update method [ID47]</a> </section>

**Comment by dr-shorthair** [comment]
Comment received by [email from Nuno Friere](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Apr/0001.html) suggests using `void:rootResource` to point to a manifest.

**Comment by dr-shorthair** [comment]
A general solution for relations from `dcat:Resource` to any other resource is discussed in #253 and a solution provided in #295. 

Guidance on use of more specific properties for relationships between` dcat:Datasets` should continue here. 
In particular considering 
(a) the more specialized DCT predicates `dct:hasPart/dct:isPartOf` , `dct:conformsTo` , `dct:isFormatOf/dct:hasFormat` , `dct:isVersionOf/dct:hasVersion` , `dct:replaces/dct:isReplacedBy` , `dct:references/dct:isReferencedBy` , `dct:requires/dct:isRequiredBy`
(b) the fully general case (possibly using qualified relation pattern and an extensible list of relationship roles) 

Should we add local (guarded) constraints on dcat:Dataset so that the range of these properties in this context is required to be `dcat:Dataset` - see discussion starting here: https://github.com/w3c/dxwg/issues/253#issuecomment-405170975

**Comment by dr-shorthair** [comment]
We should leverage the [IANA link relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml) for the general case. 
Perhaps as the value of a specified 'role' property on a qualified relationship #79. 
e.g. 
```
ex:Test987
  a dcat:Dataset ; 
  dcat:qualifiedRelation [
    a dcat:QualifiedRelationship ;
    dcat:target <http://example.org/Test123> ;
    dcat:relationRole "canonical" ;
  ] ;
.
```

**Comment by dr-shorthair** [comment]
I made a proposal for this in the Wiki page: https://github.com/w3c/dxwg/wiki/Qualified-relations#related-datasets

**Comment by davebrowning** [comment]
Now that we have introduced `dcat:DataService`, does the above requirement apply to those catalogued resources as well?  In particular,  we have specific properties tying `dcat:Dataset` to `dcat:Distribution` to `dcat:DataDistributionService` (`dcat:accessService`) and back to `dcat:Dataset` (`dcat:servesDataset`) but this kind of general requirement seems to suggest an additional/parallel mechanism is desired - or am I missing something?

**Comment by dr-shorthair** [comment]
General approach to relations in #651
