### ISSUE TITLE
Related vocabularies comparision [RVC]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#87]
<section class='requirement' id='RVC'><h3>Related vocabularies comparision [<a href='https://www.w3.org/TR/dcat-ucr#RVC' target='_blank'>RVC</a>]</h3><p>Analyse and compare similar concepts defined by vocabularies related to DCAT (e.g. VOID, Data Cube dataset).</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID36' target='_blank'>Cross-vocabulary relationships [ID36]</a> </section>

**Comment by andrea-perego** [comment]
As there has been no further discussion on this issue, I propose to close it.

**Comment by riccardoAlbertoni** [comment]
Closing this issue because the joint use with other vocabularies is already mentioned in the DCAT 2 Rec. DCAT Recommendation works under the Open Assumption, prescribing specific mapping on other vocabularies might depend on the use cases, a deeper comparison among vocabularies seems not core at this stage of work. (See resolution https://www.w3.org/2021/02/03-dxwgdcat-minutes.html#r03)

**Comment by andrea-perego** [comment]
Thanks, @riccardoAlbertoni .

Closing.
