### ISSUE TITLE
dcat conformance question

### ISSUE THREAD

**Issue by smrgeoinfo** [w3c/dxwg#967]
Section 4 on conformance states:
"Access to data is organized into datasets, distributions, and data-services.
An RDF description of the catalog itself and its datasets, distributions, and data-services is available"

then in section 5:
"Member items in a catalog should be members of one of the sub-classes, or of a sub-class of these, or of a sub-class of dcat:Resource defined in a DCAT profile or other DCAT application. dcat:Resource is effectively an extension point for defining a catalog of any kind of resource."

Question-- If I extend dcat:Resource to describe e.g. software, a vocabulary, an API or other resoruce but defining other subclasses of dcat:Resource,  will my catalog be a DCAT catalog?

**Comment by dr-shorthair** [comment]
Good question Steve. I think per section 4 the answer is strictly 'no' but the wording in section 5 does leave that door open, so section 5 needs to be tightened a bit, else section 4 tweaked to allow for this. 

The question is whether a catalog that is designed consistent with DCAT design, but whose contents describe things other than datasets or dataservices, should be considered a conformant DCAT catalog. I could swing either way, so would be interested in other views.

**Comment by riccardoAlbertoni** [comment]
@dr-shorthair wrote:
> The question is whether a catalog that is designed consistent with DCAT design, but whose contents describe things other than datasets or dataservices, should be considered a conformant DCAT catalog

I tend to say 'yes'. Otherwise, we risk discouraging the use of DCAT in unforeseen scenarios.

Let us be rather inclusive and let the users decide by themselves whether when and how DCAT can serve or not their non-data catalogs.    

A catalog of non-data resources would interoperate only on the notion of "catalog" and "resource" but I can't exclude this is useful for someone. Why should we exclude this? Is there any concrete risk I am not seeing?

In my opinion, the overall message of DCAT is clear: "Use it for Data catalog,"  and edge cases like the one discussed by Richard does not put it at risk.

**Comment by pwin** [comment]
I think we should be comfortable with much wider usage than just cataloging 'data' content to any other type of asset.  The key use of DCAT imo is the publication on the web of a catalogue of resources .  most anything that we catalogue will be some sort of information

**Comment by smrgeoinfo** [comment]
I agree -- I think the catalog framework defined in the current spec has wide potential application that could be useful. I am working on a [resource registry for the US NSF EarthCube project](https://www.earthcube.org/resource_registry), and although our serialization is currently required to use schema.org, the conceptual framework in DCAT can be applied to all the resources of interest, and dcat provides useful extensions to sdo that we can use. 

Perhaps a conformance statement along the lines of
 'a conformant catalog must define a base dcat:Catalog entity, and must consist of a collection of member items that are subclassed from dcat:Resource.  Subclasses of dcat:Resource must not define properties that duplicate existing properties in the dcat classes defined in this specification, but are free to add additional properties with distinct semantics as required.'

**Comment by riccardoAlbertoni** [comment]
>Subclasses of dcat:Resource must not define properties that duplicate existing properties in the dcat classes defined in this specification

IMO, If they duplicate existing properties is not a problem,  that might be needed to interoperate with other metadata schemes.  The issue is if they use not-dcat properties in place of the recommended properties.

I would rather opt for mentioning cataloged resources explicitly in the second and third item of section 4,  (text in bold indicates the changes compared with the current working draft formulation)
 

- An RDF description of the catalog itself and its datasets, distributions, ***data-services, and other cataloged resources (if any)*** is available (but the choice of RDF syntax, access protocol, and access policy are not mandated by this specification).
- The contents of all metadata fields that are held in the catalog and that contain data about the catalog itself and its datasets, distributions, ***data-services, and other cataloged resources (if any)*** are included in this RDF description and are expressed using the appropriate classes and properties from DCAT, except where no such class or property exists.

**Comment by smrgeoinfo** [comment]
Good point, duplication is OK, as long as the corresponding DCAT properties are also populated. 

The intention would be more like

> Subclasses of dcat:Resource must not define properties that replace existing properties in the dcat classes defined in this specification

I think your second bullet point expresses this.
